'use client';

import { ArrowLeft, MessageCircle, ShoppingCart } from 'lucide-react';
import { useEffect, useState } from 'react';
import { SiteFooter, SiteHeader } from '../components/site-chrome';
import { supplierLogo, supplierMonogram, getCuratedProductDetails } from '../supplier-product-utils';
import { readSupplierCatalogProduct } from '../supplier-catalog-cache';
import { PurchaseTerms } from '../components/purchase-terms';
import { SupplierPriceSummary } from '../components/supplier-price-summary';

type SupplierProduct = { id:string; name:string; description?:string; warranty?:string; price:number; original_price_pkr?:number|null; available:number; provider_name?:string; logo_url?:string };

export default function SupplierProductPage() {
  const [product,setProduct] = useState<SupplierProduct|null>(null);
  const [loading,setLoading] = useState(true);
  useEffect(() => { const id = new URLSearchParams(window.location.search).get('product'); if (!id) { setLoading(false); return; } const cached = readSupplierCatalogProduct<SupplierProduct>(id); if (cached) { setProduct(cached); setLoading(false); } let active = true; fetch(`/api/commerce?action=catalog&productId=${encodeURIComponent(id)}`).then((response) => response.ok ? response.json() : Promise.reject()).then((data:any) => { if (active) setProduct((data.products || [])[0] || null); }).catch(() => {}).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);

  const description = product?.description || 'The supplier did not provide a product description for this listing.';
  const logo = product ? supplierLogo(product.name, product.logo_url) : '';
return <main><SiteHeader /><div className="detail-shell supplier-detail-shell"><a href="/inventory" className="back-link"><ArrowLeft className="h-4 w-4" /> Full inventory</a>{loading ? <p className="supplier-loading">Loading product details...</p> : product ? <div className="detail-layout"><article className="detail-content"><div className="detail-identity"><div className="detail-logo-frame supplier-detail-logo">{logo ? <img src={logo} alt={`${product.name} logo`} /> : <span aria-label={`${product.name} logo`}>{supplierMonogram(product.name)}</span>}</div><div><span className="section-kicker">Instant delivery</span><h1>{product.name}</h1></div></div><section className="description-section"><h2>Supplier description</h2><div className="supplier-description-raw">{description}</div></section><section className="description-section"><h2>Product description</h2><div className="curated-product-container">{(() => { const curated = getCuratedProductDetails(product); return (<><p className="curated-intro-text">{curated.summary}</p><ul className="curated-feature-list">{curated.bullets.map((b) => (<li key={b.label} className="curated-bullet-item"><span className="curated-bullet-dot" aria-hidden="true" /><span className="curated-bullet-text"><strong>{b.label}:</strong> {b.detail}</span></li>))}</ul>{curated.activationNote ? (<div className="curated-delivery-badge"><strong>⚡ Activation:</strong> {curated.activationNote}</div>) : null}</>); })()}</div>{product.warranty && <p><strong>{product.warranty}</strong></p>}<p>After payment verification, this product is fulfilled automatically. Availability and activation details are confirmed before delivery.</p></section></article><aside className="purchase-summary" aria-label="Product purchase options"><span className="section-kicker">Ready to order</span><h2>{product.name}</h2><dl className="detail-prices"><SupplierPriceSummary product={product} /></dl><p className="purchase-mobile-delivery">Automatic delivery after payment verification</p><PurchaseTerms mobileOnly><p>Read the complete product description, activation requirements, duration and warranty terms before payment.</p></PurchaseTerms><a href={`/checkout?product=${encodeURIComponent(product.id)}`} className="primary-button detail-buy"><ShoppingCart className="h-5 w-5" /> Buy online</a><p className="order-footnote">WhatsApp support will be available after successful payment.</p><button type="button" className="whatsapp-purchase detail-buy" disabled><MessageCircle className="h-5 w-5" /> WhatsApp support <span>(after payment)</span></button></aside></div> : <section className="empty-state"><h1>Product unavailable</h1><p>This product could not be loaded.</p><a href="/inventory" className="primary-button">Back to inventory</a></section>}</div><SiteFooter /></main>;
}
