/** Display-only copy. Never use translations as identifiers or request values. */
export const languages = [
  { code: 'en', label: 'English', htmlLang: 'en' },
  { code: 'ur-Latn', label: 'Roman Urdu', htmlLang: 'ur-Latn' },
  { code: 'vi', label: 'Tiếng Việt', htmlLang: 'vi' },
] as const;
export type Language = typeof languages[number]['code'];
export const languagePreferenceKey = 'sasify-language';
export function isLanguage(value: unknown): value is Language {
  return languages.some(language => language.code === value);
}
export function isPublicPath(path: string) {
  return !/^\/(?:orders-admin|team)(?:\/|$)/.test(path);
}

// English is the source of truth. Unknown supplier copy and server errors stay
// in English; no translation service receives order or customer information.
const copy: Array<[string, string, string]> = [
  ['Language', 'Zabaan', 'Ngôn ngữ'],
  ['Choose language', 'Zabaan chunain', 'Chọn ngôn ngữ'],
  ['Main navigation', 'Main navigation', 'Điều hướng chính'],
  ['Open menu', 'Menu kholain', 'Mở menu'],
  ['Close menu', 'Menu band karain', 'Đóng menu'],
  ['Skip to content', 'Seedha content par jayen', 'Đến nội dung chính'],
  ['Home', 'Home', 'Trang chủ'],
  ['Full Inventory', 'Tamam products', 'Tất cả sản phẩm'],
  ['Full inventory', 'Tamam products', 'Tất cả sản phẩm'],
  ['Categories', 'Categories', 'Danh mục'],
  ['Scam reports', 'Scam reports', 'Báo cáo lừa đảo'],
  ['FAQ', 'Aam sawalat', 'Câu hỏi thường gặp'],
  ['Contact Us', 'Hum se rabta karain', 'Liên hệ'],
  ['Log in', 'Log in karain', 'Đăng nhập'],
  ['Sign up', 'Account banayen', 'Đăng ký'],
  ['My dashboard', 'Mera dashboard', 'Bảng điều khiển của tôi'],
  ['Display currency', 'Price ki currency', 'Đơn vị tiền hiển thị'],
  ['Digital Tools &', 'Digital Tools aur', 'Công cụ số &'],
  ['Subscriptions', 'Subscriptions', 'Gói đăng ký'],
  ['Find the right tool for your next big idea.', 'Apne aglay baray idea ke liye sahi tool dhoondain.', 'Tìm công cụ phù hợp cho ý tưởng lớn tiếp theo.'],
  ['Explore top products', 'Popular products dekhain', 'Khám phá sản phẩm nổi bật'],
  ['Request a tool', 'Tool ki request karain', 'Yêu cầu công cụ'],
  ['Get OTP', 'OTP hasil karain', 'Lấy mã OTP'],
  ['Get OTP / 2FA code', 'OTP / 2FA code hasil karain', 'Lấy mã OTP / 2FA'],
  ['Search products', 'Products dhoondain', 'Tìm sản phẩm'],
  ['Search products, categories or features', 'Product, category ya feature dhoondain', 'Tìm sản phẩm, danh mục hoặc tính năng'],
  ['Search catalog', 'Catalog mein dhoondain', 'Tìm trong danh mục'],
  ['Clear search', 'Search saaf karain', 'Xóa tìm kiếm'],
  ['Show matching products', 'Matching products dekhain', 'Hiển thị sản phẩm phù hợp'],
  ['Top selling products', 'Popular products', 'Sản phẩm bán chạy'],
  ['Matching products', 'Matching products', 'Sản phẩm phù hợp'],
  ['No matching products.', 'Koi matching product nahi mila.', 'Không có sản phẩm phù hợp.'],
  ['Show top products', 'Popular products dekhain', 'Hiển thị sản phẩm nổi bật'],
  ['Sasify Solutions Inventory', 'Sasify Solutions ke products', 'Danh mục Sasify Solutions'],
  ['Top 8 products', 'Top 8 products', '8 sản phẩm nổi bật'],
  ['View full inventory', 'Tamam products dekhain', 'Xem tất cả sản phẩm'],
  ['Explore products', 'Products dekhain', 'Khám phá sản phẩm'],
  ['Explore Products', 'Products dekhain', 'Khám phá sản phẩm'],
  ['Browse tools', 'Tools dekhain', 'Khám phá công cụ'],
  ['Browse all products', 'Tamam products dekhain', 'Xem tất cả sản phẩm'],
  ['All products', 'Tamam products', 'Tất cả sản phẩm'],
  ['All', 'Tamam', 'Tất cả'],
  ['In stock', 'Available', 'Còn hàng'],
  ['Out of stock', 'Stock khatam', 'Hết hàng'],
  ['Check availability', 'Availability check karain', 'Kiểm tra tình trạng hàng'],
  ['Checking availability…', 'Availability check ho rahi hai…', 'Đang kiểm tra tình trạng hàng…'],
  ['Currently Unavailable', 'Filhal available nahi', 'Hiện không có sẵn'],
  ['Contact for availability', 'Availability ke liye rabta karain', 'Liên hệ để kiểm tra tình trạng hàng'],
  ['Review access, duration and requirements before ordering.', 'Order se pehle access, duration aur requirements parhain.', 'Xem quyền truy cập, thời hạn và yêu cầu trước khi đặt hàng.'],
  ['Original price', 'Original price', 'Giá tham chiếu'],
  ['Our price', 'Hamari price', 'Giá của chúng tôi'],
  ['Price may vary', 'Price farq ho sakti hai', 'Giá có thể thay đổi'],
  ['Your savings', 'Aap ki bachat', 'Bạn tiết kiệm'],
  ['View details', 'Details dekhain', 'Xem chi tiết'],
  ['Buy now', 'Abhi khareedain', 'Mua ngay'],
  ['Buy online', 'Online khareedain', 'Mua trực tuyến'],
  ['Buy with Sasify Wallet', 'Sasify Wallet se khareedain', 'Mua bằng Sasify Wallet'],
  ['Compare plans', 'Plans compare karain', 'So sánh các gói'],
  ['Choose package', 'Package chunain', 'Chọn gói'],
  ['From', 'Shuru hota hai', 'Từ'],
  ['No products found', 'Koi product nahi mila', 'Không tìm thấy sản phẩm'],
  ['Try another search or category.', 'Doosri search ya category try karain.', 'Thử từ khóa hoặc danh mục khác.'],
  ['Show all products', 'Tamam products dikhayen', 'Hiển thị tất cả sản phẩm'],
  ['Sort by', 'Tarteeb', 'Sắp xếp theo'],
  ['Featured', 'Featured', 'Nổi bật'],
  ['Price: low to high', 'Price: kam se zyada', 'Giá: thấp đến cao'],
  ['Price: high to low', 'Price: zyada se kam', 'Giá: cao đến thấp'],
  ['Name: A–Z', 'Naam: A–Z', 'Tên: A–Z'],
  ['Availability', 'Availability', 'Tình trạng hàng'],
  ['In Stock Products Only', 'Sirf in-stock products', 'Chỉ sản phẩm còn hàng'],
  ['Group by Tool', 'Tools ke hisaab se group karain', 'Nhóm theo công cụ'],
  ['In stock only', 'Sirf in-stock', 'Chỉ còn hàng'],
  ['Reset filters', 'Filters reset karain', 'Đặt lại bộ lọc'],
  ['Browse by what you want to do', 'Apne kaam ke mutabiq tools dekhain', 'Khám phá theo nhu cầu của bạn'],
  ['A better way to find your next tool.', 'Apna agla tool dhoondna ab aur aasan.', 'Cách tốt hơn để tìm công cụ tiếp theo.'],
  ['Compare access, duration and pricing in one place.', 'Access, duration aur price aik jagah compare karain.', 'So sánh quyền truy cập, thời hạn và giá tại một nơi.'],
  ['AI & research', 'AI aur research', 'AI & nghiên cứu'],
  ['Design & creative', 'Design aur creative', 'Thiết kế & sáng tạo'],
  ['Video & audio', 'Video aur audio', 'Video & âm thanh'],
  ['Coding & developer tools', 'Coding aur developer tools', 'Lập trình & công cụ phát triển'],
  ['Productivity & business', 'Productivity aur business', 'Năng suất & kinh doanh'],
  ['Privacy & security', 'Privacy aur security', 'Quyền riêng tư & bảo mật'],
  ['Learn & grow', 'Seekhain aur barhain', 'Học tập & phát triển'],
  ['Entertainment', 'Entertainment', 'Giải trí'],
  ['AI Assistants & Research', 'AI assistants aur research', 'Trợ lý AI & nghiên cứu'],
  ['Design & Creative Tools', 'Design aur creative tools', 'Thiết kế & công cụ sáng tạo'],
  ['AI coding tools', 'AI coding tools', 'Công cụ lập trình AI'],
  ['Productivity & Business', 'Productivity aur business', 'Năng suất & kinh doanh'],
  ['VPNS & Security', 'VPN aur security', 'VPN & bảo mật'],
  ['Product categories', 'Product categories', 'Danh mục sản phẩm'],
  ['Previous categories', 'Pichli categories', 'Danh mục trước'],
  ['Next categories', 'Agli categories', 'Danh mục tiếp theo'],
  ['Loading supplier products...', 'Supplier products load ho rahe hain...', 'Đang tải sản phẩm từ nhà cung cấp...'],
  ['Supplier products are temporarily unavailable.', 'Supplier products filhal available nahi.', 'Sản phẩm từ nhà cung cấp tạm thời không khả dụng.'],
  ['5% discount applies on all products when you pay with Sasify Wallet.', 'Sasify Wallet se payment par tamam products par 5% discount milta hai.', 'Thanh toán bằng Sasify Wallet được giảm 5% cho tất cả sản phẩm.'],
  ['Built around trust', 'Bharosay par mabni', 'Được xây dựng trên sự tin cậy'],
  ['Why choose Sasify?', 'Sasify kyun chunain?', 'Tại sao chọn Sasify?'],
  ['Founder-led service', 'Founder ki nigrani mein service', 'Dịch vụ do nhà sáng lập điều hành'],
  ['Customer satisfaction first', 'Customer ki tasalli sab se pehle', 'Sự hài lòng của khách hàng là ưu tiên'],
  ['Competitive rates with warranty', 'Munāsib prices aur warranty', 'Giá cạnh tranh kèm bảo hành'],
  ['Genuine subscriptions only', 'Sirf genuine subscriptions', 'Chỉ cung cấp gói đăng ký chính hãng'],
  ['24/7 chat support', '24/7 chat support', 'Hỗ trợ chat 24/7'],
  ['Fair issue resolution', 'Maslay ka munasib hal', 'Giải quyết vấn đề công bằng'],
  ['A personal-brand agency led and overseen by Syed Sarosh.', 'Syed Sarosh ki nigrani mein personal-brand agency.', 'Đơn vị thương hiệu cá nhân do Syed Sarosh điều hành và giám sát.'],
  ['Clear communication, correct delivery and dependable after-sales support come first.', 'Saaf baat, durust delivery aur bharosaymand after-sales support hamari priority hai.', 'Giao tiếp rõ ràng, giao hàng chính xác và hỗ trợ sau bán hàng đáng tin cậy là ưu tiên.'],
  ['Each product has its own stated warranty terms. ChatGPT retains its listed warranty.', 'Har product ki apni di gayi warranty terms hain. ChatGPT ki listed warranty barqarar hai.', 'Mỗi sản phẩm có điều kiện bảo hành riêng. ChatGPT giữ nguyên bảo hành được công bố.'],
  ['Every plan is supplied as the access type described, with no fake subscriptions or misleading labels.', 'Har plan described access type ke mutabiq milta hai; fake subscription ya ghalat label nahi.', 'Mỗi gói được cung cấp đúng loại quyền truy cập mô tả, không có gói giả hoặc nhãn gây hiểu lầm.'],
  ['Our support team is available around the clock, including late-night assistance.', 'Hamari support team din raat madad ke liye available hai.', 'Đội ngũ hỗ trợ luôn sẵn sàng, kể cả vào ban đêm.'],
  ['If an eligible issue cannot be resolved, the remaining unused amount is refunded under the confirmed order terms.', 'Eligible masla hal na ho to confirmed order terms ke mutabiq baqi unused amount refund hoti hai.', 'Nếu vấn đề đủ điều kiện không thể giải quyết, số tiền chưa sử dụng còn lại được hoàn theo điều kiện đơn hàng đã xác nhận.'],
  ['Trusted by digital buyers', 'Digital buyers ka bharosa', 'Được khách hàng sản phẩm số tin tưởng'],
  ['Customer feedback on Google', 'Google par customer feedback', 'Phản hồi khách hàng trên Google'],
  ['Previous review', 'Pichla review', 'Đánh giá trước'],
  ['Next review', 'Agla review', 'Đánh giá tiếp theo'],
  ['Read original on Google', 'Google par original parhain', 'Đọc bản gốc trên Google'],
  ['Recent successful deliveries', 'Recent successful deliveries', 'Các đơn giao thành công gần đây'],
  ['Real order confirmations', 'Asli order confirmations', 'Xác nhận đơn hàng thực tế'],
  ['Delivery confirmations', 'Delivery confirmations', 'Xác nhận giao hàng'],
  ['Private details hidden', 'Private details chhupayi gayi hain', 'Thông tin riêng tư đã được ẩn'],
  ['After-sales support', 'After-sales support', 'Hỗ trợ sau bán hàng'],
  ['Successfully delivered', 'Delivery complete', 'Đã giao thành công'],
  ['Open delivery screenshot', 'Delivery screenshot kholain', 'Mở ảnh chụp giao hàng'],
  ['Close screenshot', 'Screenshot band karain', 'Đóng ảnh chụp'],
  ['Flexible ways to pay', 'Payment ke mukhtalif tareeqay', 'Nhiều cách thanh toán'],
  ['Supported payment methods worldwide', 'Supported payment methods worldwide', 'Phương thức thanh toán được hỗ trợ trên toàn cầu'],
  ['Common questions', 'Aam sawalat', 'Câu hỏi thường gặp'],
  ['Simple, direct purchasing', 'Aasan, seedhi purchasing', 'Mua hàng đơn giản, trực tiếp'],
  ['Choose a product, review its terms and complete checkout online.', 'Product chunain, us ki terms parhain aur online checkout mukammal karain.', 'Chọn sản phẩm, xem điều khoản và hoàn tất thanh toán trực tuyến.'],
  ['How do I place an order?', 'Order kaise karoon?', 'Làm thế nào để đặt hàng?'],
  ['Are the original prices current?', 'Kya original prices current hain?', 'Giá tham chiếu có cập nhật không?'],
  ['Do one-year plans need monthly payments?', 'Kya aik saal ke plan ke liye monthly payment chahiye?', 'Gói một năm có cần thanh toán hàng tháng không?'],
  ['Do all products come with a warranty?', 'Kya tamam products ki warranty hai?', 'Tất cả sản phẩm có bảo hành không?'],
  ['Is shared access the same as a personal plan?', 'Kya shared access personal plan jaisa hai?', 'Quyền truy cập dùng chung có giống gói cá nhân không?'],
  ['Who operates Sasify Solutions?', 'Sasify Solutions kaun chalata hai?', 'Ai điều hành Sasify Solutions?'],
  ['When is availability confirmed?', 'Availability kab confirm hoti hai?', 'Khi nào tình trạng hàng được xác nhận?'],
  ['Your Satisfaction is Our Priority', 'Aap ki tasalli hamari priority hai', 'Sự hài lòng của bạn là ưu tiên của chúng tôi'],
  ['Founder:', 'Founder:', 'Nhà sáng lập:'],
  ['About Sasify Solutions', 'Sasify Solutions ke baray mein', 'Về Sasify Solutions'],
  ['Buying guide', 'Kharidari ki guide', 'Hướng dẫn mua hàng'],
  ['Browse products', 'Products dekhain', 'Xem sản phẩm'],
  ['Warranty', 'Warranty', 'Bảo hành'],
  ['Refunds', 'Refunds', 'Hoàn tiền'],
  ['Privacy', 'Privacy', 'Quyền riêng tư'],
  ['Terms', 'Terms', 'Điều khoản'],
  ['Policies', 'Policies', 'Chính sách'],
  ['Sasify Solutions policies', 'Sasify Solutions ki policies', 'Chính sách Sasify Solutions'],
  ['Related policies', 'Related policies', 'Chính sách liên quan'],
  ['Breadcrumb', 'Page ka rasta', 'Điều hướng trang'],
  ['Your selected plan', 'Aap ka selected plan', 'Gói bạn đã chọn'],
  ['Full description', 'Mukammal description', 'Mô tả đầy đủ'],
  ['About this subscription', 'Is subscription ke baray mein', 'Về gói đăng ký này'],
  ['About this account', 'Is account ke baray mein', 'Về tài khoản này'],
  ['About this service', 'Is service ke baray mein', 'Về dịch vụ này'],
  ['Popular uses', 'Aam istemal', 'Cách sử dụng phổ biến'],
  ['Related searches', 'Mutaliqa talashain', 'Tìm kiếm liên quan'],
  ['Related product searches', 'Product ki mutaliqa talashain', 'Tìm kiếm sản phẩm liên quan'],
  ['Private plan', 'Private plan', 'Gói riêng tư'],
  ['Shared plan', 'Shared plan', 'Gói dùng chung'],
  ['What is the ChatGPT Plus price in Pakistan?', 'Pakistan mein ChatGPT Plus ki price kya hai?', 'Giá ChatGPT Plus tại Pakistan là bao nhiêu?'],
  ['This one-month ChatGPT Plus subscription is the private Ultra Stable account paid through Apple Pay. It costs PKR 3,499 at Sasify Solutions and can be purchased through online checkout.', 'Yeh aik mahine ka private Ultra Stable ChatGPT Plus plan hai jo Apple Pay se liya gaya hai. Sasify Solutions par is ki price PKR 3,499 hai aur aap ise website par online checkout se khareed sakte hain.', 'Gói ChatGPT Plus một tháng này là tài khoản Ultra Stable riêng tư, được thanh toán qua Apple Pay. Giá tại Sasify Solutions là PKR 3.499 và bạn có thể mua qua thanh toán trực tuyến.'],
  ['What warranty comes with ChatGPT Plus?', 'ChatGPT Plus ke saath kya warranty milti hai?', 'ChatGPT Plus có bảo hành gì?'],
  ['The Ultra Stable Apple Pay option includes a full 30-day warranty. Warranty details for other account options are shown on their listings. WhatsApp support is available after payment for delivery or activation issues.', 'Ultra Stable Apple Pay option ke saath poore 30 din ki warranty milti hai. Doosre account options ki warranty un ki listings mein di gayi hai. Payment ke baad delivery ya activation ke maslay par WhatsApp support available hai.', 'Gói Ultra Stable Apple Pay có bảo hành đầy đủ 30 ngày. Điều kiện bảo hành của các lựa chọn tài khoản khác được ghi trên trang tương ứng. Sau khi thanh toán, hỗ trợ WhatsApp dành cho các vấn đề giao hàng hoặc kích hoạt.'],
  ['One-month ChatGPT Plus access for advanced models, higher limits, file analysis, image generation and productivity workflows.', 'Aik mahine ka ChatGPT Plus access: advanced models, zyada usage limits, file analysis, image generation aur productivity ke kaam.', 'Quyền truy cập ChatGPT Plus một tháng với các mô hình nâng cao, giới hạn sử dụng cao hơn, phân tích tệp, tạo ảnh và công việc năng suất.'],
  ['Draft, rewrite and summarize writing or documents.', 'Likhnay, dobara likhnay aur documents ka khulasa bananay ke liye.', 'Soạn thảo, viết lại và tóm tắt văn bản hoặc tài liệu.'],
  ['Explain code, debug errors and work on software projects with Codex, subject to the plan’s usage limits.', 'Code samjhnay, errors theek karnay aur Codex se software projects par kaam karnay ke liye; plan ki usage limits lagu hoti hain.', 'Giải thích mã, sửa lỗi và làm dự án phần mềm với Codex, tùy theo giới hạn sử dụng của gói.'],
  ['Generate and refine images, ideas and presentations.', 'Images, ideas aur presentations bananay aur behtar karnay ke liye.', 'Tạo và chỉnh sửa hình ảnh, ý tưởng và bài thuyết trình.'],
  ['Explore research questions, study topics and everyday planning.', 'Research, study aur rozana planning ke liye.', 'Khám phá câu hỏi nghiên cứu, chủ đề học tập và lập kế hoạch hằng ngày.'],
  ['Design website and app screens, wireframes and interactive prototypes.', 'Website aur app screens, wireframes aur interactive prototypes design karnay ke liye.', 'Thiết kế màn hình web và ứng dụng, wireframe và nguyên mẫu tương tác.'],
  ['Collaborate on interface designs and hand off assets to developers.', 'Interface designs par team ke saath kaam aur assets developers ko hand off karnay ke liye.', 'Cộng tác thiết kế giao diện và bàn giao tài nguyên cho lập trình viên.'],
  ['Before you order', 'Order se pehle', 'Trước khi đặt hàng'],
  ['Questions about this plan', 'Is plan ke baray mein sawalat', 'Câu hỏi về gói này'],
  ['More plans to explore', 'Mazeed plans dekhain', 'Khám phá thêm các gói'],
  ['Package', 'Package', 'Gói'],
  ['Access type', 'Access ki qisam', 'Loại quyền truy cập'],
  ['Access period / allocation', 'Access ki muddat / allocation', 'Thời hạn / hạn mức truy cập'],
  ['Order support', 'Order support', 'Hỗ trợ đơn hàng'],
  ['Provider pricing reference', 'Provider ki pricing reference', 'Tham chiếu giá nhà cung cấp'],
  ['Original Pricing (full plan)', 'Original price (poora plan)', 'Giá tham chiếu (toàn bộ gói)'],
  ['Our Pricing', 'Hamari price', 'Giá của chúng tôi'],
  ['Your Savings', 'Aap ki bachat', 'Bạn tiết kiệm'],
  ['Please read before purchasing', 'Kharidne se pehle zaroor parhain', 'Vui lòng đọc trước khi mua'],
  ['Included with this Apple Pay plan.', 'Is Apple Pay plan mein shamil hai.', 'Được bao gồm trong gói Apple Pay này.'],
  ['WhatsApp support (after payment)', 'WhatsApp support (payment ke baad)', 'Hỗ trợ WhatsApp (sau thanh toán)'],
  ['Review the access and activation details above, then complete checkout online.', 'Upar access aur activation details parhain, phir online checkout mukammal karain.', 'Xem chi tiết truy cập và kích hoạt ở trên, rồi thanh toán trực tuyến.'],
  ['Please read the complete product description, activation requirements, duration and warranty terms before payment. If an issue arises because the description or requirements were not read or followed, Sasify Solutions cannot be held responsible.', 'Payment se pehle mukammal product description, activation requirements, duration aur warranty terms parhain. Agar inhein na parhne ya follow na karne ki wajah se masla ho to Sasify Solutions zimmedar nahi hogi.', 'Vui lòng đọc đầy đủ mô tả sản phẩm, yêu cầu kích hoạt, thời hạn và điều kiện bảo hành trước khi thanh toán. Sasify Solutions không chịu trách nhiệm nếu vấn đề phát sinh do không đọc hoặc không tuân thủ mô tả hay yêu cầu.'],
  ['Your Sasify account', 'Aap ka Sasify account', 'Tài khoản Sasify của bạn'],
  ['YOUR SASIFY ACCOUNT', 'AAP KA SASIFY ACCOUNT', 'TÀI KHOẢN SASIFY CỦA BẠN'],
  ['Welcome back', 'Dobara khush aamdeed', 'Chào mừng trở lại'],
  ['Welcome back.', 'Dobara khush aamdeed.', 'Chào mừng trở lại.'],
  ['Create your account', 'Apna account banayen', 'Tạo tài khoản của bạn'],
  ['Create account', 'Account banayen', 'Tạo tài khoản'],
  ['Name', 'Naam', 'Tên'],
  ['Full name', 'Poora naam', 'Họ và tên'],
  ['Your name', 'Aap ka naam', 'Tên của bạn'],
  ['Email', 'Email', 'Email'],
  ['Email address', 'Email address', 'Địa chỉ email'],
  ['Your email', 'Aap ka email', 'Email của bạn'],
  ['Phone', 'Phone', 'Điện thoại'],
  ['Phone number', 'Phone number', 'Số điện thoại'],
  ['Password', 'Password', 'Mật khẩu'],
  ['Confirm password', 'Password dobara likhain', 'Xác nhận mật khẩu'],
  ['New password', 'Naya password', 'Mật khẩu mới'],
  ['Show password', 'Password dikhayen', 'Hiển thị mật khẩu'],
  ['Hide password', 'Password chhupayen', 'Ẩn mật khẩu'],
  ['Forgot password?', 'Password bhool gaye?', 'Quên mật khẩu?'],
  ['Forgot your password?', 'Apna password bhool gaye?', 'Bạn quên mật khẩu?'],
  ['Reset password', 'Password reset karain', 'Đặt lại mật khẩu'],
  ['Password recovery', 'Password recovery', 'Khôi phục mật khẩu'],
  ['Back to login', 'Login par wapas', 'Quay lại đăng nhập'],
  ['Send reset link', 'Reset link bhejain', 'Gửi liên kết đặt lại'],
  ['Send code', 'Code bhejain', 'Gửi mã'],
  ['Verify email', 'Email verify karain', 'Xác minh email'],
  ['Verify code', 'Code verify karain', 'Xác minh mã'],
  ['Verification code', 'Verification code', 'Mã xác minh'],
  ['Resend code', 'Code dobara bhejain', 'Gửi lại mã'],
  ['Sending...', 'Bheja ja raha hai...', 'Đang gửi...'],
  ['Verifying...', 'Verify ho raha hai...', 'Đang xác minh...'],
  ['Please wait...', 'Intezaar karain...', 'Vui lòng đợi...'],
  ['Continue', 'Aagay barhain', 'Tiếp tục'],
  ['Already have an account?', 'Pehle se account hai?', 'Đã có tài khoản?'],
  ['Don’t have an account?', 'Account nahi hai?', 'Chưa có tài khoản?'],
  ["Don't have an account?", 'Account nahi hai?', 'Chưa có tài khoản?'],
  ['Dashboard', 'Dashboard', 'Bảng điều khiển'],
  ['Overview', 'Overview', 'Tổng quan'],
  ['Wallet', 'Wallet', 'Ví'],
  ['Orders', 'Orders', 'Đơn hàng'],
  ['My orders', 'Mere orders', 'Đơn hàng của tôi'],
  ['Profile', 'Profile', 'Hồ sơ'],
  ['Account sections', 'Account sections', 'Các mục tài khoản'],
  ['Log out', 'Log out karain', 'Đăng xuất'],
  ['Logout', 'Log out karain', 'Đăng xuất'],
  ['Browse products', 'Products dekhain', 'Khám phá sản phẩm'],
  ['Wallet balance', 'Wallet balance', 'Số dư ví'],
  ['Available balance', 'Available balance', 'Số dư khả dụng'],
  ['Add funds', 'Funds add karain', 'Nạp tiền'],
  ['Add money', 'Paise add karain', 'Nạp tiền'],
  ['Amount', 'Amount', 'Số tiền'],
  ['Payment method', 'Payment ka tareeqa', 'Phương thức thanh toán'],
  ['Recent orders', 'Recent orders', 'Đơn hàng gần đây'],
  ['View all', 'Sab dekhain', 'Xem tất cả'],
  ['Total orders', 'Kul orders', 'Tổng đơn hàng'],
  ['Delivered', 'Delivered', 'Đã giao'],
  ['Pending', 'Pending', 'Đang chờ'],
  ['Total savings', 'Kul bachat', 'Tổng tiết kiệm'],
  ['No orders yet', 'Abhi koi order nahi', 'Chưa có đơn hàng'],
  ['No orders yet.', 'Abhi koi order nahi.', 'Chưa có đơn hàng.'],
  ['Quick actions', 'Quick actions', 'Thao tác nhanh'],
  ['Save changes', 'Changes save karain', 'Lưu thay đổi'],
  ['Saving...', 'Save ho raha hai...', 'Đang lưu...'],
  ['Refresh', 'Refresh', 'Làm mới'],
  ['Need help?', 'Madad chahiye?', 'Cần trợ giúp?'],
  ['Contact support', 'Support se rabta karain', 'Liên hệ hỗ trợ'],
  ['Awaiting payment', 'Payment ka intezaar', 'Đang chờ thanh toán'],
  ['pending', 'Pending', 'Đang chờ'],
  ['delivered', 'Delivered', 'Đã giao'],
  ['cancelled', 'Cancelled', 'Đã hủy'],
  ['review', 'Review ho raha hai', 'Đang xem xét'],
  ['approved', 'Approved', 'Đã duyệt'],
  ['rejected', 'Rejected', 'Đã từ chối'],
  ['completed', 'Completed', 'Đã hoàn tất'],
  ['expired', 'Expired', 'Đã hết hạn'],
  ['Application pending', 'Application pending hai', 'Đơn đăng ký đang chờ'],
  ['Apply as a reseller', 'Reseller banne ki request karain', 'Đăng ký làm đại lý'],
  ['Required by Sasify', 'Sasify ki requirements', 'Nhu cầu của Sasify'],
  ['No open requirements right now.', 'Filhal koi open requirement nahi.', 'Hiện không có yêu cầu đang mở.'],
  ['Your free order', 'Aap ka free order', 'Đơn hàng miễn phí của bạn'],
  ['All products', 'Tamam products', 'Tất cả sản phẩm'],
  ['Wallet transfer', 'Wallet se transfer', 'Chuyển khoản ví'],
  ['Bank transfer', 'Bank se transfer', 'Chuyển khoản ngân hàng'],
  ['Crypto deposit', 'Crypto se payment', 'Nạp tiền mã hóa'],
  ['All banks', 'Tamam banks', 'Tất cả ngân hàng'],
  ['Easypaisa, JazzCash, NayaPay, SadaPay and more', 'Easypaisa, JazzCash, NayaPay, SadaPay aur doosray wallets', 'Easypaisa, JazzCash, NayaPay, SadaPay và các ví khác'],
  ['Binance Pay in USDT', 'Binance Pay se USDT mein', 'Binance Pay bằng USDT'],
  ['Send USDT on the displayed network', 'Dikhaye gaye network par USDT bhejain', 'Gửi USDT qua mạng được hiển thị'],
  ['HOR covered the full price. Your account credentials are ready below.', 'HOR ne poori price cover kar di hai. Aap ki login details neeche tayyar hain.', 'HOR đã thanh toán toàn bộ. Thông tin đăng nhập của bạn ở bên dưới.'],
  ['After payment, our team will process your personal email manually and deliver access from the admin panel.', 'Payment ke baad hamari team aap ka personal email manually process kar ke access degi.', 'Sau thanh toán, đội ngũ sẽ xử lý email cá nhân và cấp quyền truy cập.'],
  ['Your delivery appears here automatically after the signed NayaPay receipt is matched.', 'NayaPay receipt match honay ke baad delivery yahin khud nazar aayegi.', 'Sản phẩm tự động hiển thị tại đây sau khi khớp biên lai NayaPay.'],
  ['Your delivery appears here automatically after the authenticated Binance receipt is matched.', 'Binance receipt match honay ke baad delivery yahin khud nazar aayegi.', 'Sản phẩm tự động hiển thị tại đây sau khi khớp biên lai Binance.'],
  ['Please read the complete product description, activation requirements, duration and warranty terms before payment. If an issue arises because the description or requirements were not read or followed, Sasify Solutions cannot be held responsible.', 'Payment se pehle product ki poori description, activation requirements, duration aur warranty terms parhain. Agar in instructions ko na parhne ya follow na karne se masla aaye to Sasify Solutions zimmedar nahi hogi.', 'Trước khi thanh toán, vui lòng đọc mô tả sản phẩm, yêu cầu kích hoạt, thời hạn và điều khoản bảo hành. Sasify Solutions không chịu trách nhiệm cho vấn đề do không đọc hoặc không tuân thủ các yêu cầu này.'],
  ['Selected', 'Chuna gaya', 'Đã chọn'],
  ['Balance:', 'Balance:', 'Số dư:'],
  ['5% discount on eligible products', 'Eligible products par 5% discount', 'Giảm 5% cho sản phẩm đủ điều kiện'],
  ['Insufficient wallet balance. Add funds first.', 'Wallet mein balance kam hai. Pehle funds add karain.', 'Số dư ví không đủ. Vui lòng nạp tiền trước.'],
  ['Insufficient wallet balance. Add funds first, then try again.', 'Wallet mein balance kam hai. Funds add kar ke dobara try karain.', 'Số dư ví không đủ. Nạp tiền rồi thử lại.'],
  ['Your previous payment window ended. Please start a new order.', 'Pichli payment ki muddat khatam ho gayi. Naya order shuru karain.', 'Thời hạn thanh toán trước đã kết thúc. Vui lòng tạo đơn mới.'],
  ['Complete your payment', 'Apni payment complete karain', 'Hoàn tất thanh toán'],
  ['Free coupon delivery', 'Free coupon delivery', 'Giao hàng bằng mã miễn phí'],
  ['Manual processing after payment', 'Payment ke baad manual processing', 'Xử lý thủ công sau thanh toán'],
  ['Automatic credential delivery', 'Login details ki automatic delivery', 'Giao thông tin truy cập tự động'],
  ['Manual', 'Manual', 'Thủ công'],
  ['Instant', 'Instant', 'Tức thì'],
  ['Select package', 'Package chunain', 'Chọn gói'],
  ['Price', 'Qeemat', 'Giá'],
  ['Available stock', 'Mojood stock', 'Hàng có sẵn'],
  ['Customer email (required by this supplier)', 'Customer email (supplier ko zaroori hai)', 'Email khách hàng (nhà cung cấp yêu cầu)'],
  ['The supplier will use this email to process and deliver your purchase.', 'Supplier aap ki purchase process aur deliver karne ke liye yeh email use karega.', 'Nhà cung cấp dùng email này để xử lý và giao sản phẩm của bạn.'],
  ['How will you send the payment?', 'Aap payment kaise bhejain ge?', 'Bạn sẽ thanh toán bằng cách nào?'],
  ['Other payment methods', 'Payment ke doosray tareeqay', 'Phương thức thanh toán khác'],
  ['Select another payment method', 'Doosra payment method chunain', 'Chọn phương thức thanh toán khác'],
  ['Sasify Wallet is selected above', 'Upar Sasify Wallet selected hai', 'Sasify Wallet được chọn ở trên'],
  ['Wallet discount (5%)', 'Wallet discount (5%)', 'Giảm giá ví (5%)'],
  ['Final amount with Sasify Wallet:', 'Sasify Wallet ke saath final amount:', 'Số tiền cuối cùng với Sasify Wallet:'],
  ['Reseller coupon', 'Reseller coupon code', 'Mã giảm giá đại lý'],
  ['(optional)', '(agar ho)', '(không bắt buộc)'],
  ['(not available with Sasify Wallet)', '(Sasify Wallet ke saath available nahi)', '(không áp dụng với Sasify Wallet)'],
  ['Enter coupon code', 'Coupon code likhain', 'Nhập mã giảm giá'],
  ['Coupons cannot be combined with Sasify Wallet payments.', 'Sasify Wallet payment ke saath coupon use nahi ho sakta.', 'Không thể kết hợp mã giảm giá với thanh toán bằng Sasify Wallet.'],
  ['Preparing checkout...', 'Checkout tayyar ho raha hai...', 'Đang chuẩn bị thanh toán...'],
  ['Pay online', 'Online payment karain', 'Thanh toán trực tuyến'],
  ['Sold out online.', 'Online stock khatam.', 'Đã hết hàng trực tuyến.'],
  ['Contact us on WhatsApp', 'WhatsApp par rabta karain', 'Liên hệ qua WhatsApp'],
  ['Loading order...', 'Order load ho raha hai...', 'Đang tải đơn hàng...'],
  ['Back to checkout', 'Checkout par wapas', 'Quay lại thanh toán'],
  ['Verifying payment', 'Payment verify ho rahi hai', 'Đang xác minh thanh toán'],
  ['Verification pending', 'Verification pending hai', 'Đang chờ xác minh'],
  ['Order cancelled', 'Order cancel ho gaya', 'Đơn hàng đã bị hủy'],
  ['Pay from your bank account', 'Apne bank account se pay karain', 'Thanh toán từ tài khoản ngân hàng'],
  ['Pay with crypto in USDT', 'Crypto se USDT mein pay karain', 'Thanh toán bằng tiền mã hóa USDT'],
  ['Pay with Binance Pay in USDT', 'Binance Pay se USDT mein pay karain', 'Thanh toán USDT qua Binance Pay'],
  ['Account title', 'Account title', 'Tên tài khoản'],
  ['Account number', 'Account number', 'Số tài khoản'],
  ['Copy', 'Copy', 'Sao chép'],
  ['Copied', 'Copy ho gaya', 'Đã sao chép'],
  ['Copied.', 'Copy ho gaya.', 'Đã sao chép.'],
  ['I have paid', 'Main ne payment kar di hai', 'Tôi đã thanh toán'],
  ['Payment submitted', 'Payment submit ho gayi', 'Đã gửi thanh toán'],
  ['Cancel order', 'Order cancel karain', 'Hủy đơn hàng'],
  ['Your delivery', 'Aap ki delivery', 'Sản phẩm đã giao của bạn'],
  ['Your account credentials', 'Aap ke account credentials', 'Thông tin truy cập tài khoản của bạn'],
  ['Download', 'Download', 'Tải xuống'],
  ['Back to products', 'Products par wapas', 'Quay lại sản phẩm'],
  ['Submit request', 'Request bhejain', 'Gửi yêu cầu'],
  ['Tool name', 'Tool ka naam', 'Tên công cụ'],
  ['Your requirements', 'Aap ki requirements', 'Yêu cầu của bạn'],
  ['Submit report', 'Report bhejain', 'Gửi báo cáo'],
  ['Details', 'Details', 'Chi tiết'],
  ['Generate code', 'Code banayen', 'Tạo mã'],
  ['2FA code', '2FA code', 'Mã 2FA'],
  ['Write, research and explore ideas.', 'Likhain, research karain aur ideas explore karain.', 'Viết, nghiên cứu và khám phá ý tưởng.'],
  ['Create visuals, video and content.', 'Visuals, video aur content banayen.', 'Tạo hình ảnh, video và nội dung.'],
  ['Build, debug and bring ideas to life.', 'Build karain, bugs hal karain aur ideas ko haqeeqat banayen.', 'Xây dựng, gỡ lỗi và hiện thực hóa ý tưởng.'],
  ['Organize your work and get more done.', 'Apna kaam organize karain aur zyada kaam complete karain.', 'Sắp xếp công việc và hoàn thành nhiều hơn.'],
  ['Explore credits and developer access.', 'Credits aur developer access dekhain.', 'Khám phá tín dụng và quyền truy cập cho lập trình viên.'],
  ['Find tools for more private browsing.', 'Private browsing ke tools dhoondain.', 'Tìm công cụ duyệt web riêng tư hơn.'],
  ['Make room for your next skill.', 'Apni agli skill ke liye jagah banayen.', 'Dành thời gian cho kỹ năng tiếp theo.'],
  ['Discover your next watch or listen.', 'Apni agli watch ya listen dhoondain.', 'Khám phá nội dung xem hoặc nghe tiếp theo.'],
  ['Tools for your next career move.', 'Apne aglay career step ke tools.', 'Công cụ cho bước tiến nghề nghiệp tiếp theo.'],
  ['Explore the rest of the collection.', 'Baqi collection dekhain.', 'Khám phá phần còn lại của bộ sưu tập.'],
  ['API & Credit Packages', 'API aur credit packages', 'API & gói tín dụng'],
  ['VPN & Privacy', 'VPN aur privacy', 'VPN & quyền riêng tư'],
  ['AI Video, Image & Creative', 'AI video, image aur creative tools', 'AI video, hình ảnh & sáng tạo'],
  ['AI Coding & Development', 'AI coding aur development', 'Lập trình & phát triển AI'],
  ['Education & Learning', 'Taleem aur learning', 'Giáo dục & học tập'],
  ['Professional & Career', 'Professional aur career', 'Chuyên môn & nghề nghiệp'],
  ['Entertainment & Streaming', 'Entertainment aur streaming', 'Giải trí & phát trực tuyến'],
  ['Other Tools', 'Doosray tools', 'Công cụ khác'],
  ['Live availability could not be checked. Open a product to confirm before ordering.', 'Live availability check nahi ho saki. Order se pehle product khol kar confirm karain.', 'Không thể kiểm tra tình trạng hàng trực tiếp. Mở sản phẩm để xác nhận trước khi đặt hàng.'],
  ["Pakistan's 1st fully automated digital store", 'Pakistan ka pehla fully automated digital store', 'Cửa hàng số hoàn toàn tự động đầu tiên của Pakistan'],
  ["Pakistan's 1st automated digital store", 'Pakistan ka pehla automated digital store', 'Cửa hàng số tự động đầu tiên của Pakistan'],
  ['Shop AI tools, digital subscriptions, and online services in Pakistan with automated delivery—search, select, pay online, and get instant digital access.', 'Pakistan mein AI tools, digital subscriptions aur online services automated delivery ke saath khareedain—search karain, chunain, online pay karain aur foran digital access hasil karain.', 'Mua công cụ AI, gói đăng ký số và dịch vụ trực tuyến tại Pakistan với giao hàng tự động—tìm kiếm, chọn, thanh toán trực tuyến và nhận quyền truy cập số ngay lập tức.'],
  ['Starting at', 'Shuru hota hai', 'Giá từ'],
  ['products in catalog', 'products catalog mein', 'sản phẩm trong danh mục'],
  ['from', 'se', 'từ'],
  ['Google reviews', 'Google reviews', 'đánh giá trên Google'],
  ['Savings compare the original price for the full plan duration with our price. Monthly references are multiplied by the number of months. Access and provider billing options may differ.', 'Savings poori plan duration ki original price aur hamari price ka farq hain. Monthly reference ko months se multiply kiya jata hai. Access aur provider billing options farq ho sakte hain.', 'Khoản tiết kiệm so sánh giá tham chiếu cho toàn bộ thời hạn gói với giá của chúng tôi. Giá tham chiếu hàng tháng được nhân với số tháng. Quyền truy cập và tùy chọn thanh toán của nhà cung cấp có thể khác.'],
  ['Wallet & deposits', 'Wallet aur deposits', 'Ví & tiền nạp'],
  ['Wallet activity', 'Wallet activity', 'Hoạt động ví'],
  ['Account details', 'Account details', 'Chi tiết tài khoản'],
  ['Account type', 'Account ki qisam', 'Loại tài khoản'],
  ['Customer', 'Customer', 'Khách hàng'],
  ['Reseller', 'Reseller', 'Đại lý'],
  ['Username', 'Username', 'Tên người dùng'],
  ['Signed in', 'Signed in', 'Đã đăng nhập'],
  ['View orders and account details', 'Orders aur account details dekhain', 'Xem đơn hàng và chi tiết tài khoản'],
  ['Pay from Sasify Wallet · 5% off', 'Sasify Wallet se pay karain · 5% off', 'Thanh toán bằng Sasify Wallet · giảm 5%'],
  ['Password must contain at least 8 characters.', 'Password mein kam az kam 8 characters hon.', 'Mật khẩu phải có ít nhất 8 ký tự.'],
  ['Your passwords do not match.', 'Aap ke passwords match nahi karte.', 'Mật khẩu không khớp.'],
  ['Reseller account', 'Reseller account', 'Tài khoản đại lý'],
  ['Become a reseller', 'Reseller banain', 'Trở thành đại lý'],
  ['Apply as reseller', 'Reseller ki application bhejain', 'Đăng ký làm đại lý'],
  ['Grow with Sasify', 'Sasify ke saath barhain', 'Phát triển cùng Sasify'],
  ['Quick links', 'Quick links', 'Liên kết nhanh'],
  ['Recent deposits', 'Recent deposits', 'Tiền nạp gần đây'],
  ['Deposit history', 'Deposit history', 'Lịch sử nạp tiền'],
  ['Create deposit request', 'Deposit request banayen', 'Tạo yêu cầu nạp tiền'],
  ['New deposit', 'Naya deposit', 'Nạp tiền mới'],
  ['No deposits yet.', 'Abhi koi deposit nahi.', 'Chưa có tiền nạp.'],
  ['Payment instructions', 'Payment instructions', 'Hướng dẫn thanh toán'],
  ['Request amount (PKR)', 'Request amount (PKR)', 'Số tiền yêu cầu (PKR)'],
  ['Cancel deposit', 'Deposit cancel karain', 'Hủy nạp tiền'],
  ['Send verification code', 'Verification code bhejain', 'Gửi mã xác minh'],
  ['Create your Sasify account', 'Apna Sasify account banayen', 'Tạo tài khoản Sasify của bạn'],
  ['Welcome to Sasify', 'Sasify mein khush aamdeed', 'Chào mừng đến Sasify'],
  ['Verify your email', 'Apna email verify karain', 'Xác minh email của bạn'],
  ['Set your password', 'Apna password set karain', 'Đặt mật khẩu của bạn'],
  ['Confirm new password', 'Naya password dobara likhain', 'Xác nhận mật khẩu mới'],
  ['Back to sign in', 'Sign in par wapas', 'Quay lại đăng nhập'],
  ['Sign in', 'Sign in karain', 'Đăng nhập'],
  ['Sign in to your account', 'Apne account mein sign in karain', 'Đăng nhập vào tài khoản'],
  ['Warranty Policy', 'Warranty policy', 'Chính sách bảo hành'],
  ['Privacy Notice', 'Privacy notice', 'Thông báo quyền riêng tư'],
  ['Refund and Resolution Policy', 'Refund aur resolution policy', 'Chính sách hoàn tiền và giải quyết vấn đề'],
  ['Terms of Service', 'Service ki terms', 'Điều khoản dịch vụ'],
  ['Warranty periods', 'Warranty ki muddat', 'Thời hạn bảo hành'],
  ['What is covered', 'Kya cover hota hai', 'Phạm vi bảo hành'],
  ['Requesting support', 'Support kaise hasil karain', 'Yêu cầu hỗ trợ'],
  ['Information you provide', 'Aap ki di hui information', 'Thông tin bạn cung cấp'],
  ['External services', 'External services', 'Dịch vụ bên ngoài'],
  ['Email verification', 'Email verification', 'Xác minh email'],
  ['Your questions and requests', 'Aap ke sawalat aur requests', 'Câu hỏi và yêu cầu của bạn'],
  ['Before you pay', 'Payment se pehle', 'Trước khi thanh toán'],
  ['When an issue occurs', 'Jab masla ho', 'Khi xảy ra vấn đề'],
  ['Refund method and timing', 'Refund ka tareeqa aur waqt', 'Phương thức và thời gian hoàn tiền'],
  ['Keep your confirmation', 'Apni confirmation sambhal kar rakhain', 'Giữ xác nhận của bạn'],
  ['Listings and orders', 'Listings aur orders', 'Sản phẩm niêm yết và đơn hàng'],
  ['Prices and savings', 'Prices aur bachat', 'Giá và khoản tiết kiệm'],
  ['Access and provider rules', 'Access aur provider rules', 'Quyền truy cập và quy định nhà cung cấp'],
  ['Names, logos and references', 'Naam, logos aur references', 'Tên, logo và tham chiếu'],
  ['Warranty, refunds and changes', 'Warranty, refunds aur changes', 'Bảo hành, hoàn tiền và thay đổi'],
  ['Warranty terms and coverage are specific to each product listing. ChatGPT retains the warranty stated for its selected account option.', 'Warranty terms aur coverage har product listing ke mutabiq hain. ChatGPT ki warranty us ke selected account option ke mutabiq barqarar hai.', 'Điều kiện và phạm vi bảo hành phụ thuộc từng sản phẩm niêm yết. ChatGPT giữ bảo hành được nêu cho tùy chọn tài khoản đã chọn.'],
  ['Sasify Solutions reviews support requests against the individual listing terms, payment record and delivery record. Supplier-sourced products retain their own stated warranty conditions.', 'Sasify Solutions har support request ko listing terms, payment record aur delivery record ke mutabiq review karti hai. Supplier products ki apni stated warranty conditions barqarar rehti hain.', 'Sasify Solutions xem xét yêu cầu hỗ trợ dựa trên điều kiện sản phẩm, hồ sơ thanh toán và hồ sơ giao hàng. Sản phẩm từ nhà cung cấp giữ các điều kiện bảo hành được công bố riêng.'],
  ['Contact us for access, activation or subscription issues during the warranty period. Follow the listed activation requirements, account or invite conditions, supported-device limits and usage rules. We assess issues and arrange the applicable correction, replacement or resolution through order support.', 'Warranty period mein access, activation ya subscription ke maslay par rabta karain. Listed activation requirements, account ya invite conditions, device limits aur usage rules follow karain. Hum masla assess kar ke order support ke zariye applicable correction, replacement ya resolution arrange karte hain.', 'Liên hệ khi gặp vấn đề về truy cập, kích hoạt hoặc đăng ký trong thời hạn bảo hành. Tuân thủ yêu cầu kích hoạt, điều kiện tài khoản hoặc lời mời, giới hạn thiết bị và quy định sử dụng. Chúng tôi đánh giá và sắp xếp việc sửa lỗi, thay thế hoặc giải quyết phù hợp qua hỗ trợ đơn hàng.'],
  ['Use the WhatsApp support button shown with your order during the confirmed warranty period.', 'Confirmed warranty period mein order par diya gaya WhatsApp support button use karain.', 'Dùng nút hỗ trợ WhatsApp trên đơn hàng trong thời hạn bảo hành đã xác nhận.'],
  ['Share the product name, listing reference, order date and a clear description of the issue.', 'Product ka naam, listing reference, order date aur maslay ki saaf description bhejain.', 'Cung cấp tên sản phẩm, mã tham chiếu, ngày đặt hàng và mô tả rõ vấn đề.'],
  ['Do not send passwords, payment PINs or one-time verification codes.', 'Passwords, payment PINs ya one-time verification codes na bhejain.', 'Không gửi mật khẩu, mã PIN thanh toán hoặc mã xác minh dùng một lần.'],
  ['This website uses online checkout for digital purchases and provides post-purchase support through WhatsApp. Learn what information is used to verify and deliver orders.', 'Website digital purchases ke liye online checkout aur purchase ke baad WhatsApp support deti hai. Janiye orders verify aur deliver karne ke liye konsi information use hoti hai.', 'Website sử dụng thanh toán trực tuyến cho sản phẩm số và hỗ trợ sau mua qua WhatsApp. Tìm hiểu thông tin được dùng để xác minh và giao đơn hàng.'],
  ['Digital purchases are paid online, verified before delivery and supported through the order screen when an issue occurs.', 'Digital purchases ki payment online hoti hai, delivery se pehle verify hoti hai aur maslay par order screen se support milti hai.', 'Sản phẩm số được thanh toán trực tuyến, xác minh trước khi giao và hỗ trợ qua màn hình đơn hàng khi xảy ra vấn đề.'],
  ['These terms explain how listings, online checkout, automatic delivery and post-purchase support work.', 'Yeh terms listings, online checkout, automatic delivery aur purchase ke baad support ka tareeqa batati hain.', 'Điều khoản này giải thích cách niêm yết, thanh toán trực tuyến, giao tự động và hỗ trợ sau mua hoạt động.'],
  ['Review the exact product, access type, duration, availability, activation steps and warranty coverage on the product page before paying through secure checkout. The checkout total and payment instructions shown for your order control the transaction.', 'Secure checkout par payment se pehle product page par exact product, access type, duration, availability, activation steps aur warranty coverage dekhain. Aap ke order ka checkout total aur payment instructions transaction par lagu hain.', 'Trước khi thanh toán, xem chính xác sản phẩm, loại quyền truy cập, thời hạn, tình trạng hàng, bước kích hoạt và bảo hành trên trang sản phẩm. Tổng tiền và hướng dẫn thanh toán hiển thị cho đơn hàng là căn cứ giao dịch.'],
  ['If a refund is approved, its amount, payment method and expected processing time will be confirmed in the support conversation. Provider reference prices and displayed savings do not determine the refund amount.', 'Refund approve ho to amount, payment method aur expected processing time support conversation mein confirm honge. Provider reference price aur displayed savings refund amount tay nahi karte.', 'Nếu hoàn tiền được duyệt, số tiền, phương thức và thời gian xử lý dự kiến được xác nhận trong cuộc trao đổi hỗ trợ. Giá tham chiếu và khoản tiết kiệm hiển thị không quyết định số tiền hoàn.'],
  ['Retain the WhatsApp order confirmation and payment record. Do not share passwords, payment PINs or one-time verification codes when requesting support.', 'WhatsApp order confirmation aur payment record sambhal kar rakhain. Support ke waqt passwords, payment PINs ya one-time verification codes share na karain.', 'Giữ xác nhận đơn hàng WhatsApp và hồ sơ thanh toán. Không chia sẻ mật khẩu, mã PIN thanh toán hoặc mã xác minh dùng một lần khi yêu cầu hỗ trợ.'],
  ['Third-party names and logos identify the relevant tools and belong to their respective owners. Unless a listing expressly states otherwise, their use does not claim that Sasify Solutions is the provider or an official affiliate.', 'Third-party names aur logos tools ki pehchan hain aur un ke owners ki milkiyat hain. Jab tak listing wazeh taur par na kahe, in ka istemal Sasify Solutions ko provider ya official affiliate nahi batata.', 'Tên và logo bên thứ ba xác định công cụ liên quan và thuộc chủ sở hữu tương ứng. Trừ khi sản phẩm nêu rõ, việc sử dụng không khẳng định Sasify Solutions là nhà cung cấp hoặc đơn vị liên kết chính thức.'],
  ['YOUR SASIFY ACCOUNT', 'AAP KA SASIFY ACCOUNT', 'TÀI KHOẢN SASIFY CỦA BẠN'],
  ['Your digital world, together.', 'Aap ki digital duniya, aik jagah.', 'Thế giới số của bạn, tất cả trong một.'],
  ['Keep your purchases, credentials and wallet together in one calm, secure space built around you.', 'Apni khareedari, login details aur wallet ko aik mehfooz jagah par rakhein.', 'Quản lý đơn mua, thông tin đăng nhập và ví trong một không gian an toàn, thuận tiện.'],
  ['Your orders, always within reach', 'Aap ke orders hamesha dastaras mein', 'Đơn hàng luôn trong tầm tay'],
  ['Secure access to purchased credentials', 'Khareedi hui login details tak mehfooz rasai', 'Truy cập an toàn thông tin đăng nhập đã mua'],
  ['Your personal Sasify wallet, with 5% off every purchase', 'Aap ka Sasify wallet, har khareedari par 5% discount ke saath', 'Ví Sasify của bạn, giảm 5% cho mỗi lần mua'],
  ['Log in to Sasify', 'Sasify mein log in karain', 'Đăng nhập Sasify'],
  ['Create your customer account in a few seconds.', 'Chand seconds mein apna customer account banayen.', 'Tạo tài khoản khách hàng chỉ trong vài giây.'],
  ['Your purchases are waiting for you.', 'Aap ki khareedari aap ki muntazir hai.', 'Các đơn mua của bạn đang chờ.'],
  ['New to Sasify?', 'Sasify par naye hain?', 'Bạn mới đến Sasify?'],
  ['Already have an account?', 'Pehle se account hai?', 'Đã có tài khoản?'],
  ['Create an account', 'Account banayen', 'Tạo tài khoản'],
  ['3–24 characters. Use letters, numbers, dots, underscores, or hyphens; start and end with a letter or number.', '3–24 characters. Letters, numbers, dots, underscores ya hyphens use karain; shuru aur aakhir letter ya number ho.', '3–24 ký tự. Dùng chữ cái, số, dấu chấm, gạch dưới hoặc gạch nối; bắt đầu và kết thúc bằng chữ hoặc số.'],
  ['YOUR SASIFY WORKSPACE', 'AAP KA SASIFY WORKSPACE', 'KHÔNG GIAN SASIFY CỦA BẠN'],
  ['RESELLER WORKSPACE', 'RESELLER WORKSPACE', 'KHÔNG GIAN ĐẠI LÝ'],
  ['Your dashboard', 'Aap ka dashboard', 'Bảng điều khiển của bạn'],
  ['Track your orders, wallet and account details.', 'Apne orders, wallet aur account details dekhein.', 'Theo dõi đơn hàng, ví và thông tin tài khoản.'],
  ['Browse products', 'Products dekhain', 'Khám phá sản phẩm'],
  ['Confirm your payment', 'Apni payment confirm karain', 'Xác nhận thanh toán'],
  ['After sending the exact amount, click below. We will match the verified payment automatically using your unique order amount.', 'Exact amount bhejne ke baad neeche click karain. Hum aap ke unique order amount se verified payment automatically match karenge.', 'Sau khi chuyển đúng số tiền, nhấn bên dưới. Chúng tôi sẽ tự động đối chiếu khoản thanh toán đã xác minh theo số tiền riêng của đơn hàng.'],
  ['Checking payment...', 'Payment check ho rahi hai...', 'Đang kiểm tra thanh toán...'],
  ['I paid — verify automatically', 'Maine payment kar di — automatic verification karain', 'Tôi đã thanh toán — xác minh tự động'],
  ['Checking your payment', 'Aap ki payment check ho rahi hai', 'Đang kiểm tra thanh toán của bạn'],
  ['Secure account delivery', 'Mehfooz account delivery', 'Giao tài khoản an toàn'],
  ['Your account credentials are ready', 'Aap ki account login details tayyar hain', 'Thông tin đăng nhập tài khoản đã sẵn sàng'],
  ['Your account is ready', 'Aap ka account tayyar hai', 'Tài khoản của bạn đã sẵn sàng'],
  ['Thank you for trusting Sasify Solutions. Your credentials are below. Keep this message private.', 'Sasify Solutions par bharosa karne ka shukriya. Aap ki login details neeche hain. Is paigham ko private rakhein.', 'Cảm ơn bạn đã tin tưởng Sasify Solutions. Thông tin đăng nhập ở bên dưới. Hãy giữ riêng tư thông báo này.'],
  ['Complete your account setup', 'Apne account ka setup mukammal karain', 'Hoàn tất thiết lập tài khoản'],
  ['Follow these steps to log in and keep your warranty active.', 'Log in aur warranty barqarar rakhne ke liye in steps par amal karain.', 'Làm theo các bước sau để đăng nhập và duy trì hiệu lực bảo hành.'],
  ['Important warranty requirement', 'Warranty ki zaroori shart', 'Yêu cầu bảo hành quan trọng'],
  ['Transfer the account to your personal email after login. Warranty support is not applicable if the account is not transferred.', 'Log in ke baad account apne personal email par transfer karain. Agar account transfer na ho to warranty support lagu nahi hoti.', 'Sau khi đăng nhập, chuyển tài khoản sang email cá nhân của bạn. Hỗ trợ bảo hành không áp dụng nếu tài khoản không được chuyển.'],
  ['Transfer to your personal email', 'Apne personal email par transfer karain', 'Chuyển sang email cá nhân'],
  ['Do not change or remove the account password or 2FA settings.', 'Account password ya 2FA settings tabdeel ya remove na karain.', 'Không thay đổi hoặc xóa mật khẩu tài khoản hay cài đặt 2FA.'],
  ['If an issue occurs, contact Sasify Solutions with your order reference.', 'Masla ho to apne order reference ke saath Sasify Solutions se rabta karain.', 'Nếu gặp vấn đề, hãy liên hệ Sasify Solutions và cung cấp mã tham chiếu đơn hàng.'],
  ['I have logged in — continue', 'Maine log in kar liya — jari rakhein', 'Tôi đã đăng nhập — tiếp tục'],
  ['Step 2: Enter your one-time 2FA code', 'Step 2: Aik martaba istemal honay wala 2FA code dalain', 'Bước 2: Nhập mã 2FA dùng một lần'],
  ['Show one-time 2FA code', 'Aik martaba wala 2FA code dikhayen', 'Hiển thị mã 2FA dùng một lần'],
  ['Generating code...', 'Code ban raha hai...', 'Đang tạo mã...'],
  ['Step 2: One-time 2FA code', 'Step 2: Aik martaba wala 2FA code', 'Bước 2: Mã 2FA dùng một lần'],
  ['Pay here and your account credentials will appear on this screen automatically after verification, usually within one minute. No manual delivery delays.', 'Yahan payment karain. Verification ke baad account login details aam tor par aik minute ke andar isi screen par khud aa jayengi. Manual delivery ka intezaar nahi.', 'Thanh toán tại đây; sau khi xác minh, thông tin đăng nhập thường tự động xuất hiện trên màn hình này trong vòng một phút. Không phải chờ giao thủ công.'],
  ['Shared account · 4 members', 'Shared account · 4 members', 'Tài khoản dùng chung · 4 thành viên'],
  ['This is shared ChatGPT Plus access. Your data and activity are not private and may be visible to other members. Usage is shared between members, so no individual usage-limit guarantee is provided.', 'Yeh shared ChatGPT Plus access hai. Aap ka data aur activity private nahi hain aur doosray members dekh sakte hain. Usage members mein shared hai, is liye kisi individual usage limit ki guarantee nahi di jati.', 'Đây là quyền truy cập ChatGPT Plus dùng chung. Dữ liệu và hoạt động của bạn không riêng tư và có thể hiển thị cho thành viên khác. Mức sử dụng được chia sẻ, vì vậy không bảo đảm hạn mức sử dụng riêng cho từng người.'],
  ['After delivery, shared access is not eligible for replacement, warranty or refund if the shared usage allowance is reached.', 'Delivery ke baad agar shared usage allowance khatam ho jaye to shared access ke liye replacement, warranty ya refund nahi milega.', 'Sau khi giao, quyền truy cập dùng chung không đủ điều kiện thay thế, bảo hành hoặc hoàn tiền nếu đã đạt giới hạn sử dụng chung.'],
  ['Includes a 25-day replacement warranty. Usage is shared; if the shared usage limit is temporarily reached, it resets automatically after a short cooldown (replacement is not provided for temporary usage exhaustion, only for login or account failure).', '25 din ki replacement warranty shamil hai. Usage shared hai; agar usage limit exhaust ho jaye toh thore waqt baad auto-reset ho jati hai (temporary exhaust par replacement nahi milti, replacement sirf login ya account breakdown par milti hai).', 'Bao gồm bảo hành thay thế 25 ngày. Quyền sử dụng được chia sẻ; nếu giới hạn sử dụng tạm hết, hệ thống sẽ tự động đặt lại sau một thời gian ngắn làm nguội (không bảo hành khi tạm hết lượt dùng, chỉ bảo hành khi lỗi đăng nhập hoặc mất tài khoản).'],
  ['Shared access · 25 Days Warranty', 'Shared access · 25 din ki warranty', 'Truy cập dùng chung · Bảo hành 25 ngày'],
  ['25-day replacement warranty included. If shared usage limit is temporarily reached, it resets automatically after a short cooldown (replacement covers login or account issues, not temporary usage resets).', '25 din ki replacement warranty shamil hai. Agar shared usage limit exhaust ho jaye toh woh thore waqt baad automatically reset ho jati hai (temporary limit exhaust par replacement nahi hogi, replacement sirf login ya account issue par milti hai).', 'Bao gồm bảo hành thay thế 25 ngày. Nếu giới hạn sử dụng chung tạm thời hết, hệ thống sẽ tự động đặt lại sau một thời gian ngắn làm nguội (bảo hành áp dụng cho sự cố đăng nhập/tài khoản, không áp dụng khi tạm hết lượt dùng).'],
  ['Includes 25-day replacement warranty. If shared usage allowance is reached, it resets automatically after a short cooldown; temporary usage exhaustion is not eligible for replacement.', '25 din ki replacement warranty shamil hai. Agar shared usage allowance khatam ho jaye toh thore waqt baad auto-reset ho jati hai; temporary limit exhaust par replacement nahi milti.', 'Bao gồm bảo hành thay thế 25 ngày. Nếu đạt giới hạn sử dụng chung, hệ thống sẽ tự động đặt lại sau một thời gian; việc tạm hết lượt dùng không được đổi mới.'],
  ['Sign up to unlock · 5% discount on eligible products', 'Sign up kar ke eligible products par 5% discount hasil karain', 'Đăng ký để mở khóa · giảm 5% cho sản phẩm đủ điều kiện'],
  ['Select another payment method', 'Payment ka doosra tareeqa chunain', 'Chọn phương thức thanh toán khác'],
  ['Sasify Wallet is selected above', 'Upar Sasify Wallet chuna gaya hai', 'Ví Sasify đã được chọn ở trên'],
  ['Wallet discount (5%)', 'Wallet discount (5%)', 'Giảm giá ví (5%)'],
  ['Reseller coupon (optional)', 'Reseller coupon (optional)', 'Mã giảm giá đại lý (tùy chọn)'],
  ['Product sections', 'Product ke sections', 'Các mục sản phẩm'],
  ['See price & purchase options', 'Price aur purchase options dekhain', 'Xem giá và lựa chọn mua'],
  ['Review the product requirements and availability before ordering.', 'Order se pehle product ki requirements aur availability dekhain.', 'Xem yêu cầu sản phẩm và tình trạng hàng trước khi đặt.'],
  ['Price comparison', 'Price ka muqabla', 'So sánh giá'],
  ['Questions about this product', 'Is product ke baray mein sawalat', 'Câu hỏi về sản phẩm này'],
  ['Questions about this plan', 'Is plan ke baray mein sawalat', 'Câu hỏi về gói này'],
  ['Choose your VPS package', 'Apna VPS package chunain', 'Chọn gói VPS của bạn'],
  ['Shared account slot', 'Shared account slot', 'Vị trí tài khoản dùng chung'],
  ['filled', 'bhar chukay', 'đã đầy'],
  ['Team access · No payment required', 'Team access · payment zaroori nahi', 'Quyền truy cập nhóm · không cần thanh toán'],
  ['Original price: PKR', 'Asal qeemat: PKR', 'Giá gốc: PKR'],
  ['Reseller discount: −PKR', 'Reseller discount: −PKR', 'Giảm giá đại lý: −PKR'],
  ['Send exactly', 'Bilkul yehi raqam bhejain', 'Gửi chính xác'],
  ['to the', 'neeche diye gaye', 'đến'],
  ['below.', 'par.', 'bên dưới.'],
  ['This lower whole-rupee amount is unique to your active order. Send the exact amount shown above.', 'Yeh kam poori-rupee raqam sirf aap ke active order ke liye hai. Upar dikhayi gayi exact raqam bhejain.', 'Số tiền nguyên rupee thấp hơn này là riêng cho đơn hàng hiện tại. Hãy gửi đúng số tiền hiển thị ở trên.'],
  ['WhatsApp support will be enabled 30 seconds after you submit payment if delivery has not completed.', 'Agar delivery complete na ho to payment submit karne ke 30 seconds baad WhatsApp support available ho jayegi.', 'Nếu chưa giao hàng, hỗ trợ WhatsApp sẽ có sau 30 giây kể từ khi gửi thanh toán.'],
  ['Payment timer', 'Payment ka baqi waqt', 'Thời gian thanh toán'],
  ['Changed your mind? Cancel this payment reservation to release the reserved stock.', 'Irada badal gaya? Reserved stock release karne ke liye yeh payment reservation cancel karain.', 'Đổi ý? Hủy giữ chỗ thanh toán để trả lại sản phẩm đã giữ.'],
  ['Cancel payment and order', 'Payment aur order cancel karain', 'Hủy thanh toán và đơn hàng'],
  ['Payment verification pending', 'Payment ki verification baqi hai', 'Đang chờ xác minh thanh toán'],
  ['We are checking for your payment receipt. Keep this page open; the order will cancel automatically in', 'Hum aap ki payment receipt check kar rahe hain. Page khula rakhain; agar payment na mili to order itnay waqt mein khud cancel ho jayega:', 'Chúng tôi đang kiểm tra biên lai. Giữ trang này mở; đơn sẽ tự hủy sau'],
  ['second', 'second', 'giây'],
  ['if no payment is found.', 'agar payment na mili.', 'nếu không tìm thấy thanh toán.'],
  ['This reservation expired. If you already paid, enter the payment confirmation below so support can review it.', 'Yeh reservation expire ho chuki hai. Agar aap pay kar chukay hain to neeche payment confirmation dein taa ke support check kar sakay.', 'Thời hạn giữ chỗ đã hết. Nếu đã thanh toán, nhập xác nhận bên dưới để bộ phận hỗ trợ kiểm tra.'],
  ['Keep this page open. It refreshes automatically and', 'Yeh page khula rakhain. Yeh khud refresh hota hai aur', 'Giữ trang này mở. Trang tự làm mới và'],
  ['WhatsApp support unlocks in', 'WhatsApp support itnay waqt mein available hogi:', 'Hỗ trợ WhatsApp sẽ mở sau'],
  ['if delivery is still pending.', 'agar delivery abhi baqi ho.', 'nếu vẫn chưa giao hàng.'],
  ['Subject:', 'Mauzoo:', 'Chủ đề:'],
  ['Order #', 'Order #', 'Đơn hàng #'],
  ['Step 1: Log in with your email and password', 'Step 1: Apne email aur password se log in karain', 'Bước 1: Đăng nhập bằng email và mật khẩu'],
  ['Log in to ChatGPT', 'ChatGPT mein log in karain', 'Đăng nhập ChatGPT'],
  ['Open ChatGPT.com and enter the Email and Password shown above.', 'ChatGPT.com khol kar upar diya gaya email aur password likhain.', 'Mở ChatGPT.com và nhập email cùng mật khẩu ở trên.'],
  ['Generate your login code', 'Apna login code banayen', 'Tạo mã đăng nhập'],
  ['Finish verification', 'Verification mukammal karain', 'Hoàn tất xác minh'],
  ['Enter the generated 6-digit code on ChatGPT immediately. The code is time-sensitive.', 'Banaya gaya 6-digit code foran ChatGPT mein likhain. Is code ki muddat kam hai.', 'Nhập ngay mã 6 chữ số vào ChatGPT. Mã có thời hạn ngắn.'],
  ['You will be shown this code only once, so handle it properly and enter it immediately on the ChatGPT 2FA login screen.', 'Yeh code sirf aik martaba dikhaya jayega, isay foran ChatGPT ki 2FA login screen par likhain.', 'Mã chỉ hiển thị một lần; hãy nhập ngay vào màn hình 2FA của ChatGPT.'],
  ['This strict action is intended to ensure that only the four assigned members access this shared account and that it is not shared beyond the four available slots.', 'Yeh zaroori qadam is liye hai ke shared account sirf chaar assigned members hi istemal karain aur aagay share na ho.', 'Bước này đảm bảo chỉ bốn thành viên được chỉ định sử dụng tài khoản dùng chung.'],
  ['The one-time 2FA code has already been issued for this order.', 'Is order ka one-time 2FA code pehle hi diya ja chuka hai.', 'Mã 2FA dùng một lần đã được cấp cho đơn hàng này.'],
  ['Your purchase is ready', 'Aap ki purchase tayyar hai', 'Sản phẩm của bạn đã sẵn sàng'],
  ['Keep this information private and follow the activation instructions below.', 'Yeh information private rakhain aur neeche activation instructions follow karain.', 'Giữ kín thông tin này và làm theo hướng dẫn kích hoạt bên dưới.'],
  ['Activation instructions', 'Activation ka tareeqa', 'Hướng dẫn kích hoạt'],
  ['Need help with this order?', 'Is order mein madad chahiye?', 'Cần hỗ trợ đơn hàng này?'],
  ['If your credentials do not work or you have any delivery or activation issue, contact our support team on WhatsApp. Your order reference is included automatically.', 'Agar login details kaam na karain ya delivery ya activation mein masla ho to WhatsApp support se rabta karain. Order reference khud shamil ho jayega.', 'Nếu thông tin đăng nhập không hoạt động hoặc gặp vấn đề giao hàng hay kích hoạt, hãy liên hệ hỗ trợ WhatsApp. Mã đơn hàng sẽ được đính kèm tự động.'],
  ['Start a new order', 'Naya order shuru karain', 'Tạo đơn hàng mới'],
  ['See top plans and prices', 'Top plans aur prices dekhain', 'Xem các gói nổi bật và giá'],
  ['Request a missing tool', 'Jo tool na mile, uski request karain', 'Yêu cầu công cụ còn thiếu'],
  ['Get your 2FA code', 'Apna 2FA code lein', 'Lấy mã 2FA của bạn'],
  ['See price and buy', 'Price dekhain aur khareedain', 'Xem giá và mua'],
  ['Every plan shows its access type, length and PKR price.', 'Har plan par access type, muddat aur PKR price likhi hai.', 'Mỗi gói hiển thị loại quyền truy cập, thời hạn và giá PKR.'],
  ['Available plans', 'Available plans', 'Các gói hiện có'],
  ['Plans by tool', 'Tool ke hisab se plans', 'Các gói theo công cụ'],
  ['Save 5% with Sasify Wallet on eligible products. Claude Team preorders are excluded.', 'Eligible products par Sasify Wallet se 5% bachayen. Claude Team preorders par yeh discount nahi milta.', 'Tiết kiệm 5% với Sasify Wallet cho sản phẩm đủ điều kiện. Không áp dụng cho đơn đặt trước Claude Team.'],
  ['Browse all tool plans', 'Tamam tools ke plans dekhain', 'Xem tất cả các gói công cụ'],
];

export const translations = Object.fromEntries(copy.map(([english, ur, vi]) => [english, { 'ur-Latn': ur, vi }])) as Record<string, Record<Exclude<Language, 'en'>, string>>;
const normalize = (value: string) => value.replace(/\s+/g, ' ').trim();
const caseInsensitiveCopy = new Map(Object.entries(translations).map(([key, pair]) => [key.toLowerCase(), pair]));

export function translateText(value: string, language: Language): string {
  if (language === 'en' || !value.trim()) return value;
  const normalized = normalize(value);
  const direct = (translations[normalized] || caseInsensitiveCopy.get(normalized.toLowerCase()))?.[language];
  if (direct) return value.replace(value.trim(), direct);
  // Presentation-only number patterns; preserve the exact original numbers.
  const patterns: Array<[RegExp, string, string]> = [
    [/^Compare all (.+) plans and prices$/, '$1 ke tamam plans aur prices compare karain', 'So sánh tất cả các gói và giá $1'],
    [/^(\d+) products$/, '$1 products', '$1 sản phẩm'],
    [/^(\d+) products in catalog$/, 'Catalog mein $1 products', '$1 sản phẩm trong danh mục'],
    [/^(\d+) products? found$/, '$1 products milay', 'Tìm thấy $1 sản phẩm'],
    [/^(\d+) available$/, '$1 available', 'Có sẵn $1'],
    [/^(\d+) in stock$/, '$1 available', 'Còn $1'],
    [/^(\d+) (?:Month|Months)$/, '$1 mahinay', '$1 tháng'],
    [/^(\d+) (?:Day|Days)$/, '$1 din', '$1 ngày'],
    [/^(\d+) (?:Year|Years)$/, '$1 saal', '$1 năm'],
    [/^Full (\d+)-day warranty$/, 'Poore $1 din ki warranty', 'Bảo hành đầy đủ $1 ngày'],
    [/^Last updated: (.+)$/, 'Aakhri update: $1', 'Cập nhật lần cuối: $1'],
    [/^Show prices in (PKR|USD)$/, 'Prices $1 mein dikhayen', 'Hiển thị giá bằng $1'],
    [/^Balance: PKR ([\d,]+) · 5% discount on eligible products$/, 'Balance: PKR $1 · eligible products par 5% discount', 'Số dư: PKR $1 · giảm 5% cho sản phẩm đủ điều kiện'],
    [/^Search (ChatGPT(?: Plus)?)$/, '$1 dhoondain', 'Tìm $1'],
    [/^Welcome back, (.+)$/, 'Dobara khush aamdeed, $1', 'Chào mừng trở lại, $1'],
    [/^Resend (\d+)s$/, '$1s mein dobara bhejain', 'Gửi lại sau $1 giây'],
  ];
  for (const [pattern, ur, vi] of patterns) if (pattern.test(normalized)) {
    return value.replace(value.trim(), normalized.replace(pattern, language === 'vi' ? vi : ur));
  }
  return value;
}
