export type Product = {
  id: string;
  slug: string;
  category: string;
  name: string;
  duration: string;
  vendor: string;
  sellingPricePkr: number;
  originalPrice: string;
  originalPricePkr?: number;
  details?: string[];
  sourceUrl: string;
  description: string;
};

export const products: Product[] = [
  {
    "id": "p093",
    "slug": "chatgpt-plus-1-month",
    "category": "AI Assistants & Research",
    "name": "ChatGPT Plus",
    "duration": "1 Month",
    "vendor": "Sasify Solutions",
    "sellingPricePkr": 3499,
    "originalPrice": "PKR 5,700/month",
    "originalPricePkr": 5700,
    "sourceUrl": "https://openai.com/chatgpt/pricing/",
    "description": "One-month ChatGPT Plus access for advanced models, higher limits, file analysis, image generation and productivity workflows."
  },
  {
    "id": "p094",
    "slug": "chatgpt-plus-shared",
    "category": "AI Assistants & Research",
    "name": "ChatGPT Plus Shared",
    "duration": "1 Month",
    "vendor": "Sasify Solutions",
    "sellingPricePkr": 999,
    "originalPrice": "ChatGPT Plus PKR 5,700/month",
    "sourceUrl": "https://openai.com/chatgpt/pricing/",
    "description": "Budget-friendly shared ChatGPT Plus access for everyday writing, research, image generation and AI assistance."
  },
  {
    "id": "p095",
    "slug": "codex-single-person",
    "category": "AI Coding & Development",
    "name": "Codex Single Person",
    "duration": "1 Month",
    "vendor": "Sasify Solutions",
    "sellingPricePkr": 1499,
    "originalPrice": "Included with eligible ChatGPT plans",
    "sourceUrl": "https://openai.com/codex/",
    "description": "Single-person Codex access for AI-assisted coding, debugging, code review and software-development workflows."
  },
  {
    "id": "p001",
    "slug": "antigravity-x20-ultra-25k-flow-credits",
    "category": "API & Credit Packages",
    "name": "Antigravity x20 Ultra - 25K Flow Credits",
    "duration": "30 Days",
    "vendor": "GPTCheap_bot",
    "sellingPricePkr": 24999,
    "originalPrice": "Original provider pricing varies by credits and access",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Antigravity Ultra package bundled with 25K Flow credits for supported AI-generation workflows."
  },
  {
    "id": "p002",
    "slug": "antigravity-x20-ultra-random-credits",
    "category": "API & Credit Packages",
    "name": "Antigravity x20 Ultra - Random Credits",
    "duration": "3 Months",
    "vendor": "GPTCheap_bot",
    "sellingPricePkr": 22999,
    "originalPrice": "Original provider pricing varies by credits and access",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Three-month Antigravity Ultra access with a variable bundled credit balance."
  },
  {
    "id": "p003",
    "slug": "antigravity-x20-ultra-random-credits",
    "category": "API & Credit Packages",
    "name": "Antigravity x20 Ultra - Random Credits",
    "duration": "30 Days",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 7999,
    "originalPrice": "Original provider pricing varies by credits and access",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Antigravity Ultra access with a variable bundled credit balance for supported AI workflows."
  },
  {
    "id": "p004",
    "slug": "claude-api-100",
    "category": "API & Credit Packages",
    "name": "Claude API $100",
    "duration": "30 Days",
    "vendor": "EM Store",
    "sellingPricePkr": 4999,
    "originalPrice": "$100 API credit face value",
    "sourceUrl": "https://docs.anthropic.com/en/api/rate-limits",
    "description": "Claude API credit package for developers integrating Anthropic language models into applications and workflows."
  },
  {
    "id": "p005",
    "slug": "claude-api-500",
    "category": "API & Credit Packages",
    "name": "Claude API $500",
    "duration": "30 Days",
    "vendor": "EM Store",
    "sellingPricePkr": 9999,
    "originalPrice": "$500 API credit face value",
    "sourceUrl": "https://docs.anthropic.com/en/api/rate-limits",
    "description": "Higher-value Claude API credit package for application development and AI-powered automation workloads."
  },
  {
    "id": "p006",
    "slug": "codex-api-100-token",
    "category": "API & Credit Packages",
    "name": "Codex API $100 Token",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 5499,
    "originalPrice": "$100 API credit face value",
    "sourceUrl": "https://openai.com/api/pricing/",
    "description": "Larger developer API token package for AI-assisted coding and programmatic development tasks."
  },
  {
    "id": "p007",
    "slug": "codex-api-50-token",
    "category": "API & Credit Packages",
    "name": "Codex API $50 Token",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 2999,
    "originalPrice": "$50 API credit face value",
    "sourceUrl": "https://openai.com/api/pricing/",
    "description": "Developer API token package intended for AI-assisted coding and software-development workflows."
  },
  {
    "id": "p008",
    "slug": "elevenlabs-redeem-300k-credits",
    "category": "API & Credit Packages",
    "name": "ElevenLabs Redeem - 300K Credits",
    "duration": "Lifetime Credits",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 2999,
    "originalPrice": "Creator $22/month or $220/year",
    "sourceUrl": "https://elevenlabs.io/pricing",
    "description": "Redeemable ElevenLabs credit package for AI voice generation and text-to-speech workloads."
  },
  {
    "id": "p009",
    "slug": "seedance-2k1-5k-credits",
    "category": "API & Credit Packages",
    "name": "Seedance 2K1 - 5K Credits",
    "duration": "1 Month",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 999,
    "originalPrice": "Official price varies by plan, region, or availability",
    "sourceUrl": "",
    "description": "AI creative credit package intended for generative video and visual-content workflows."
  },
  {
    "id": "p010",
    "slug": "antigravity-x20-ultra-0-credits",
    "category": "AI Assistants & Research",
    "name": "Antigravity x20 Ultra - 0 Credits",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot / FatBunny Hub",
    "sellingPricePkr": 6999,
    "originalPrice": "Original provider pricing varies by credits and access",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "High-tier Antigravity access variant supplied without bundled Flow credits."
  },
  {
    "id": "p011",
    "slug": "antigravity-x20-ultra-0-credits",
    "category": "AI Assistants & Research",
    "name": "Antigravity x20 Ultra - 0 Credits",
    "duration": "1 Year",
    "vendor": "GPTCheap_bot",
    "sellingPricePkr": 37999,
    "originalPrice": "Original provider pricing varies by credits and access",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Long-duration Antigravity Ultra access supplied without bundled Flow credits."
  },
  {
    "id": "p012",
    "slug": "claude-team-plan-premium",
    "category": "AI Assistants & Research",
    "name": "Claude Team Plan Premium",
    "duration": "1 Month",
    "vendor": "Zoom Store",
    "sellingPricePkr": 24999,
    "originalPrice": "US$125 per seat/month, billed monthly (before tax)",
    "sourceUrl": "https://claude.com/pricing",
    "description": "One-month Claude Team Premium seat for demanding writing, research, coding and document-analysis workflows, with higher usage capacity than a Standard seat.",
    "details": ["Premium is the higher-usage seat type within Claude Team, not an API credit package.", "Claude Team includes Claude Code and Cowork. Feature access remains subject to the workspace settings and provider limits.", "The original price shown is Anthropic's monthly US per-seat reference. Provider minimum-seat requirements and regional taxes may apply when purchasing directly."]
  },
  {
    "id": "p013",
    "slug": "claude-team-plan-standard",
    "category": "AI Assistants & Research",
    "name": "Claude Team Plan Standard",
    "duration": "1 Month",
    "vendor": "Zoom Store / Alternate Supplier",
    "sellingPricePkr": 4999,
    "originalPrice": "US$25 per seat/month, billed monthly (before tax)",
    "sourceUrl": "https://claude.com/pricing",
    "description": "One-month Claude Team Standard seat for AI-assisted writing, research, document analysis and coding in a team workspace.",
    "details": ["Standard is the entry seat type within Claude Team, with usage limits set by Anthropic.", "Claude Team includes Claude Code and Cowork. Feature access remains subject to the workspace settings and provider limits.", "The original price shown is Anthropic's monthly US per-seat reference. Provider minimum-seat requirements and regional taxes may apply when purchasing directly."]
  },
  {
    "id": "p014",
    "slug": "elevenlabs-creator",
    "category": "AI Assistants & Research",
    "name": "ElevenLabs Creator",
    "duration": "12 Months",
    "vendor": "Akunding_store",
    "sellingPricePkr": 19999,
    "originalPrice": "Creator $22/month or $220/year",
    "sourceUrl": "https://elevenlabs.io/pricing",
    "description": "AI voice platform plan for realistic text-to-speech, voice generation and audio content creation."
  },
  {
    "id": "p015",
    "slug": "gamma-pro",
    "category": "AI Assistants & Research",
    "name": "Gamma Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro $20/month or $192/year",
    "sourceUrl": "https://gamma.app/pricing",
    "description": "AI presentation and document creation tool for quickly building polished decks, pages and visual content."
  },
  {
    "id": "p016",
    "slug": "gemini-ai-pro",
    "category": "AI Assistants & Research",
    "name": "Gemini AI Pro",
    "duration": "18 Months",
    "vendor": "Gemini Shop",
    "sellingPricePkr": 2999,
    "originalPrice": "Google AI Pro $19.99/month",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Extended-access Google AI plan for Gemini-powered research, writing and productivity features."
  },
  {
    "id": "p017",
    "slug": "gemini-ai-pro",
    "category": "AI Assistants & Research",
    "name": "Gemini AI Pro",
    "duration": "3 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 999,
    "originalPrice": "Google AI Pro $19.99/month",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Google AI subscription tier for advanced Gemini features and AI-assisted productivity."
  },
  {
    "id": "p018",
    "slug": "gemini-ultra-antigravity-x5",
    "category": "AI Assistants & Research",
    "name": "Gemini Ultra / Antigravity x5",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 6999,
    "originalPrice": "Google AI Ultra $249.99/month",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Gemini/Antigravity access tier intended for higher-capacity AI workflows and supported generation features."
  },
  {
    "id": "p019",
    "slug": "grok-heavy-cdk",
    "category": "AI Assistants & Research",
    "name": "Grok Heavy CDK",
    "duration": "1 Month",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 24999,
    "originalPrice": "SuperGrok Heavy $300/month",
    "sourceUrl": "https://x.ai/grok",
    "description": "High-usage Grok AI access intended for advanced conversational, research and content-generation workflows."
  },
  {
    "id": "p020",
    "slug": "manus-pro",
    "category": "AI Assistants & Research",
    "name": "Manus Pro",
    "duration": "12 Months",
    "vendor": "Akunding_store",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro plan pricing varies by region",
    "sourceUrl": "https://manus.im/pricing",
    "description": "AI agent subscription intended for handling research, creation and multi-step productivity tasks."
  },
  {
    "id": "p021",
    "slug": "perplexity-enterprise-pro",
    "category": "AI Assistants & Research",
    "name": "Perplexity Enterprise Pro",
    "duration": "1 Month",
    "vendor": "Qamify",
    "sellingPricePkr": 2499,
    "originalPrice": "Enterprise Pro commonly from $40/user/month",
    "sourceUrl": "https://www.perplexity.ai/enterprise",
    "description": "AI answer and research engine plan for searching the web and receiving concise answers backed by sources."
  },
  {
    "id": "p022",
    "slug": "perplexity-max",
    "category": "AI Assistants & Research",
    "name": "Perplexity Max",
    "duration": "1 Month",
    "vendor": "MKE Shop",
    "sellingPricePkr": 24999,
    "originalPrice": "Max $200/month",
    "sourceUrl": "https://www.perplexity.ai/pricing",
    "description": "High-tier Perplexity access intended for intensive AI research, search and advanced productivity usage."
  },
  {
    "id": "p023",
    "slug": "perplexity-pro",
    "category": "AI Assistants & Research",
    "name": "Perplexity Pro",
    "duration": "1 Month",
    "vendor": "MKE Shop",
    "sellingPricePkr": 4499,
    "originalPrice": "Pro $20/month or $200/year",
    "sourceUrl": "https://www.perplexity.ai/pricing",
    "description": "Advanced Perplexity research access with enhanced AI search, deeper answers and premium research features."
  },
  {
    "id": "p024",
    "slug": "perplexity-pro",
    "category": "AI Assistants & Research",
    "name": "Perplexity Pro",
    "duration": "1 Year",
    "vendor": "MKE Shop",
    "sellingPricePkr": 9999,
    "originalPrice": "Pro $20/month or $200/year",
    "sourceUrl": "https://www.perplexity.ai/pricing",
    "description": "Annual advanced Perplexity research access for AI-powered search, sourced answers and deeper research."
  },
  {
    "id": "p025",
    "slug": "supergrok",
    "category": "AI Assistants & Research",
    "name": "SuperGrok",
    "duration": "7 Days",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 1499,
    "originalPrice": "SuperGrok $30/month",
    "sourceUrl": "https://x.ai/grok",
    "description": "Short-duration Grok AI access for conversational assistance, research and content-generation features."
  },
  {
    "id": "p026",
    "slug": "adobe-express",
    "category": "AI Video, Image & Creative",
    "name": "Adobe Express",
    "duration": "12 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 1999,
    "originalPrice": "$9.99/month or $99.99/year",
    "sourceUrl": "https://www.adobe.com/express/pricing",
    "description": "Design and content-creation app for social graphics, videos, templates and quick branded content."
  },
  {
    "id": "p027",
    "slug": "capcut-pro",
    "category": "AI Video, Image & Creative",
    "name": "CapCut Pro",
    "duration": "6 Months",
    "vendor": "Akunding_store",
    "sellingPricePkr": 4999,
    "originalPrice": "Pro pricing varies by region and platform",
    "sourceUrl": "https://www.capcut.com/pricing",
    "description": "Premium video editing plan for social content, effects, captions, transitions and advanced editing tools."
  },
  {
    "id": "p028",
    "slug": "capcut-pro-team",
    "category": "AI Video, Image & Creative",
    "name": "CapCut Pro Team",
    "duration": "1 Month",
    "vendor": "EM Store",
    "sellingPricePkr": 999,
    "originalPrice": "Pro pricing varies by region and platform",
    "sourceUrl": "https://www.capcut.com/pricing",
    "description": "AI-powered video editor with trimming, effects, captions, background removal and creator tools."
  },
  {
    "id": "p029",
    "slug": "descript-creator",
    "category": "AI Video, Image & Creative",
    "name": "Descript Creator",
    "duration": "1 Year",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 6999,
    "originalPrice": "Creator $24/month or $144/year",
    "sourceUrl": "https://www.descript.com/pricing",
    "description": "Audio and video editor with transcript-based editing, recording and AI-assisted content-production tools."
  },
  {
    "id": "p030",
    "slug": "google-veo-3-ultra-extension",
    "category": "AI Video, Image & Creative",
    "name": "Google Veo 3 Ultra Extension",
    "duration": "30 Days",
    "vendor": "Qamify",
    "sellingPricePkr": 2499,
    "originalPrice": "Included with Google AI Ultra $249.99/month",
    "sourceUrl": "https://one.google.com/about/google-ai-plans/",
    "description": "Google AI video-generation access intended for creating video content from prompts and creative inputs."
  },
  {
    "id": "p031",
    "slug": "higgsfield-pro",
    "category": "AI Video, Image & Creative",
    "name": "Higgsfield Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP / Akunding_store",
    "sellingPricePkr": 29999,
    "originalPrice": "Pro pricing varies by credit bundle",
    "sourceUrl": "https://higgsfield.ai/pricing",
    "description": "Generative AI platform focused on creating stylized images and video content with creative controls."
  },
  {
    "id": "p032",
    "slug": "leonardo-ai-essential-8-500-credits",
    "category": "AI Video, Image & Creative",
    "name": "Leonardo AI Essential - 8,500 Credits",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 1499,
    "originalPrice": "Essential from $10/month",
    "sourceUrl": "https://leonardo.ai/pricing/",
    "description": "Generative image platform credits for creating and editing AI-generated visual content."
  },
  {
    "id": "p033",
    "slug": "meitu-vip",
    "category": "AI Video, Image & Creative",
    "name": "Meitu VIP+",
    "duration": "30 Days",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 1499,
    "originalPrice": "VIP+ pricing varies by region/app store",
    "sourceUrl": "https://www.meitu.com/en/",
    "description": "Premium photo and beauty editing access for retouching, filters and creative image-editing features."
  },
  {
    "id": "p034",
    "slug": "runway-pro",
    "category": "AI Video, Image & Creative",
    "name": "Runway Pro",
    "duration": "12 Months",
    "vendor": "Akunding_store",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro $35/month or $336/year",
    "sourceUrl": "https://runwayml.com/pricing",
    "description": "Creative AI plan for generative video, image tools and professional content-production workflows."
  },
  {
    "id": "p035",
    "slug": "supercut-pro-10-seat",
    "category": "AI Video, Image & Creative",
    "name": "Supercut Pro - 10 Seat",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 4999,
    "originalPrice": "Official pricing varies by seats",
    "sourceUrl": "https://www.supercut.ai/",
    "description": "Team plan for creating and sharing polished screen recordings and asynchronous video communication."
  },
  {
    "id": "p036",
    "slug": "bolt-pro",
    "category": "AI Coding & Development",
    "name": "Bolt Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 8999,
    "originalPrice": "Pro from $20/month",
    "sourceUrl": "https://bolt.new/pricing",
    "description": "AI development environment for generating, editing and building web applications from natural-language prompts."
  },
  {
    "id": "p037",
    "slug": "chatprd",
    "category": "AI Coding & Development",
    "name": "ChatPRD",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 2999,
    "originalPrice": "Paid plan from about $15/month",
    "sourceUrl": "https://www.chatprd.ai/pricing",
    "description": "AI product-management assistant for drafting product requirements, planning and product documentation."
  },
  {
    "id": "p038",
    "slug": "gumloop-pro",
    "category": "AI Coding & Development",
    "name": "Gumloop Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 4999,
    "originalPrice": "Pro pricing varies by usage tier",
    "sourceUrl": "https://www.gumloop.com/pricing",
    "description": "No-code AI automation platform for creating workflows that connect models, data and business tools."
  },
  {
    "id": "p039",
    "slug": "jam-team-10-seat",
    "category": "AI Coding & Development",
    "name": "Jam Team - 10 Seat",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 8999,
    "originalPrice": "Team from about $10/user/month",
    "sourceUrl": "https://jam.dev/pricing",
    "description": "Team collaboration tool for capturing bug reports and sharing contextual feedback during product development."
  },
  {
    "id": "p040",
    "slug": "linear-business",
    "category": "AI Coding & Development",
    "name": "Linear Business",
    "duration": "12 Months",
    "vendor": "Zoom Store",
    "sellingPricePkr": 14999,
    "originalPrice": "Business $15/user/month",
    "sourceUrl": "https://linear.app/pricing",
    "description": "Issue tracking and product-development workspace for planning, managing and shipping software projects."
  },
  {
    "id": "p041",
    "slug": "lovable-lite",
    "category": "AI Coding & Development",
    "name": "Lovable Lite",
    "duration": "12 Months",
    "vendor": "Zoom Store / Alternate Supplier",
    "sellingPricePkr": 4449,
    "originalPrice": "Starter from $25/month",
    "sourceUrl": "https://lovable.dev/pricing",
    "description": "AI-assisted application builder for quickly turning ideas and prompts into functional web projects."
  },
  {
    "id": "p042",
    "slug": "lovable-pro",
    "category": "AI Coding & Development",
    "name": "Lovable Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP / Akunding_store",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro from $50/month",
    "sourceUrl": "https://lovable.dev/pricing",
    "description": "AI-assisted app and website builder for turning natural-language ideas into working software projects."
  },
  {
    "id": "p043",
    "slug": "magic-patterns-starter",
    "category": "AI Coding & Development",
    "name": "Magic Patterns Starter",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 4999,
    "originalPrice": "Starter from $19/month",
    "sourceUrl": "https://www.magicpatterns.com/pricing",
    "description": "AI design tool for generating and iterating on UI concepts, components and product interfaces."
  },
  {
    "id": "p044",
    "slug": "n8n-starter",
    "category": "AI Coding & Development",
    "name": "n8n Starter",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP / Akunding_store",
    "sellingPricePkr": 14999,
    "originalPrice": "Starter from EUR 20/month",
    "sourceUrl": "https://n8n.io/pricing/",
    "description": "Workflow automation platform for connecting apps, APIs and automating repetitive business processes."
  },
  {
    "id": "p045",
    "slug": "posthog-scale",
    "category": "AI Coding & Development",
    "name": "PostHog Scale",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 6999,
    "originalPrice": "Usage-based pricing",
    "sourceUrl": "https://posthog.com/pricing",
    "description": "Product analytics platform for understanding user behavior, events, funnels and product performance."
  },
  {
    "id": "p046",
    "slug": "railway-hobby",
    "category": "AI Coding & Development",
    "name": "Railway Hobby",
    "duration": "12 Months",
    "vendor": "Akunding_store",
    "sellingPricePkr": 6999,
    "originalPrice": "Hobby $5/month",
    "sourceUrl": "https://railway.com/pricing",
    "description": "Cloud deployment platform plan for hosting applications, services and databases with developer-friendly workflows."
  },
  {
    "id": "p047",
    "slug": "railway-pro",
    "category": "AI Coding & Development",
    "name": "Railway Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro $20/month",
    "sourceUrl": "https://railway.com/pricing",
    "description": "Professional cloud deployment plan for hosting applications, services and databases."
  },
  {
    "id": "p048",
    "slug": "replit-core",
    "category": "AI Coding & Development",
    "name": "Replit Core",
    "duration": "12 Months",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 9999,
    "originalPrice": "Core $25/month",
    "sourceUrl": "https://replit.com/pricing",
    "description": "Cloud development plan for building, running and collaborating on software projects with AI coding tools."
  },
  {
    "id": "p049",
    "slug": "resend-pro",
    "category": "AI Coding & Development",
    "name": "Resend Pro",
    "duration": "12 Months",
    "vendor": "Zoom Store",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro $20/month",
    "sourceUrl": "https://resend.com/pricing",
    "description": "Developer email platform plan for sending transactional and application-generated email."
  },
  {
    "id": "p050",
    "slug": "supabase-pro",
    "category": "AI Coding & Development",
    "name": "Supabase Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP / Akunding_store",
    "sellingPricePkr": 14999,
    "originalPrice": "Pro $25/month",
    "sourceUrl": "https://supabase.com/pricing",
    "description": "Backend development platform plan with database, authentication, storage and application infrastructure features."
  },
  {
    "id": "p051",
    "slug": "warp-build",
    "category": "AI Coding & Development",
    "name": "Warp Build",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 4999,
    "originalPrice": "Paid plan from $15/month",
    "sourceUrl": "https://www.warp.dev/pricing",
    "description": "Developer productivity plan centered on an intelligent terminal and AI-assisted coding workflows."
  },
  {
    "id": "p052",
    "slug": "granola-business",
    "category": "Productivity & Business",
    "name": "Granola Business",
    "duration": "-",
    "vendor": "CHIRAG OTT SHOP / Akunding_store",
    "sellingPricePkr": 4999,
    "originalPrice": "Business from $18/user/month",
    "sourceUrl": "https://www.granola.ai/pricing",
    "description": "AI meeting-notes workspace designed to capture, organize and summarize conversations and notes."
  },
  {
    "id": "p053",
    "slug": "icloud-2tb-slot",
    "category": "Productivity & Business",
    "name": "iCloud 2TB Slot",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 1699,
    "originalPrice": "$9.99/month",
    "sourceUrl": "https://support.apple.com/en-us/108047",
    "description": "Cloud-storage access slot intended for additional iCloud storage capacity."
  },
  {
    "id": "p054",
    "slug": "ilovepdf-premium",
    "category": "Productivity & Business",
    "name": "iLovePDF Premium",
    "duration": "1 Year",
    "vendor": "Dodi Store",
    "sellingPricePkr": 999,
    "originalPrice": "Premium pricing varies by monthly/yearly plan",
    "sourceUrl": "https://www.ilovepdf.com/pricing",
    "description": "PDF productivity suite for merging, splitting, compressing, converting and editing PDF documents."
  },
  {
    "id": "p055",
    "slug": "microsoft-365-admin-5-slots",
    "category": "Productivity & Business",
    "name": "Microsoft 365 Admin - 5 Slots",
    "duration": "6 Months",
    "vendor": "GPTCheap_bot",
    "sellingPricePkr": 4999,
    "originalPrice": "Microsoft 365 business plans from $6/user/month",
    "sourceUrl": "https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products",
    "description": "Multi-slot Microsoft 365 access intended for productivity apps, collaboration and account administration."
  },
  {
    "id": "p056",
    "slug": "microsoft-office-365-plus",
    "category": "Productivity & Business",
    "name": "Microsoft Office 365 Plus",
    "duration": "12 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 1999,
    "originalPrice": "Microsoft 365 Personal $99.99/year",
    "sourceUrl": "https://www.microsoft.com/en-us/microsoft-365/buy/compare-all-microsoft-365-products",
    "description": "Productivity suite access for Office apps and cloud-based document, spreadsheet and presentation workflows."
  },
  {
    "id": "p057",
    "slug": "microsoft-office-365-premium-1tb-onedrive",
    "category": "Productivity & Business",
    "name": "Microsoft Office 365 Premium + 1TB OneDrive",
    "duration": "12 Months",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 4999,
    "originalPrice": "Microsoft 365 Family $129.99/year",
    "sourceUrl": "https://www.microsoft.com/en-us/microsoft-365/buy/compare-all-microsoft-365-products",
    "description": "Microsoft productivity suite access bundled with 1TB of OneDrive cloud storage."
  },
  {
    "id": "p058",
    "slug": "notion-business",
    "category": "Productivity & Business",
    "name": "Notion Business",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP / Akunding_store",
    "sellingPricePkr": 5999,
    "originalPrice": "Business $20/user/month",
    "sourceUrl": "https://www.notion.com/pricing",
    "description": "Collaborative workspace for documents, databases, projects, knowledge management and team organization."
  },
  {
    "id": "p059",
    "slug": "outlook-mail",
    "category": "Productivity & Business",
    "name": "Outlook Mail",
    "duration": "-",
    "vendor": "Zoom Store",
    "sellingPricePkr": 49,
    "originalPrice": "Outlook.com is free; Microsoft 365 adds paid mailbox benefits",
    "sourceUrl": "https://www.microsoft.com/en-us/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook",
    "description": "Microsoft email account access for sending, receiving and managing email through Outlook services."
  },
  {
    "id": "p060",
    "slug": "quillbot-premium",
    "category": "Productivity & Business",
    "name": "QuillBot Premium",
    "duration": "1 Month",
    "vendor": "Dodi Store",
    "sellingPricePkr": 999,
    "originalPrice": "Premium $19.95/month",
    "sourceUrl": "https://quillbot.com/premium",
    "description": "AI writing assistant for paraphrasing, grammar improvement, rewriting, summarization and writing support."
  },
  {
    "id": "p061",
    "slug": "wispr-flow-pro",
    "category": "Productivity & Business",
    "name": "Wispr Flow Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 6999,
    "originalPrice": "Pro pricing varies by billing plan",
    "sourceUrl": "https://wisprflow.ai/pricing",
    "description": "Voice dictation and productivity tool for turning natural speech into clean written text across workflows."
  },
  {
    "id": "p062",
    "slug": "canva-business",
    "category": "Design & UI/UX",
    "name": "Canva Business",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 14999,
    "originalPrice": "Teams from $10/user/month annual billing",
    "sourceUrl": "https://www.canva.com/pricing/",
    "description": "Business-oriented Canva access for collaborative design, brand content, templates and team workflows."
  },
  {
    "id": "p096",
    "slug": "canva-pro-invite-1-year",
    "category": "Design & UI/UX",
    "name": "Canva Pro Invite",
    "duration": "1 Year",
    "vendor": "Sasify Solutions",
    "sellingPricePkr": 999,
    "originalPrice": "Pro from $15/month",
    "sourceUrl": "https://www.canva.com/pricing/",
    "description": "One-year Canva Pro invite for creating designs, presentations and social-media content with Canva's design tools.",
    "details": [
      "One invite for one year of access. Confirm your account email and activation requirements with Sasify Solutions before payment.",
      "PKR 999 is a one-time payment to Sasify Solutions for the full year. No monthly payments to us are required."
    ]
  },
  {
    "id": "p063",
    "slug": "canva-pro-panel",
    "category": "Design & UI/UX",
    "name": "Canva Pro Panel",
    "duration": "499 Invites",
    "vendor": "Dodi Store",
    "sellingPricePkr": 4999,
    "originalPrice": "Pro from $15/month",
    "sourceUrl": "https://www.canva.com/pricing/",
    "description": "Multi-invite Canva panel intended for managing access to collaborative Canva design features."
  },
  {
    "id": "p064",
    "slug": "canva-pro-team-edu-invite",
    "category": "Design & UI/UX",
    "name": "Canva Pro Team EDU Invite",
    "duration": "3 Years",
    "vendor": "Dodi Store",
    "sellingPricePkr": 4999,
    "originalPrice": "Pro from $15/month",
    "sourceUrl": "https://www.canva.com/pricing/",
    "description": "Canva access for collaborative graphic design, templates, presentations and social-media content creation."
  },
  {
    "id": "p065",
    "slug": "figma-pro-edu",
    "category": "Design & UI/UX",
    "name": "Figma Pro EDU",
    "duration": "2 Years",
    "vendor": "Dodi Store",
    "sellingPricePkr": 6999,
    "originalPrice": "Professional from $16/seat/month",
    "sourceUrl": "https://www.figma.com/pricing/",
    "description": "Collaborative interface design platform for UI/UX design, prototyping, components and team workflows."
  },
  {
    "id": "p066",
    "slug": "figma-pro-education",
    "category": "Design & UI/UX",
    "name": "Figma Pro Education",
    "duration": "1 Year",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 6999,
    "originalPrice": "Professional from $16/seat/month",
    "sourceUrl": "https://www.figma.com/pricing/",
    "description": "Collaborative UI/UX design and prototyping access with professional Figma design workflows."
  },
  {
    "id": "p067",
    "slug": "framer-pro",
    "category": "Design & UI/UX",
    "name": "Framer Pro",
    "duration": "12 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 6999,
    "originalPrice": "Pro from $30/site/month",
    "sourceUrl": "https://www.framer.com/pricing/",
    "description": "Professional website design and publishing platform for responsive sites, animations and collaborative design."
  },
  {
    "id": "p068",
    "slug": "miro-premium",
    "category": "Design & UI/UX",
    "name": "Miro Premium",
    "duration": "1-3 Years",
    "vendor": "Zoom Store",
    "sellingPricePkr": 1499,
    "originalPrice": "Starter $8/member/month; Business $16/member/month",
    "sourceUrl": "https://miro.com/pricing/",
    "description": "Collaborative visual workspace for whiteboarding, brainstorming, planning and team workshops."
  },
  {
    "id": "p069",
    "slug": "mobbin-10x-seat",
    "category": "Design & UI/UX",
    "name": "Mobbin 10x Seat",
    "duration": "12 Months",
    "vendor": "Akunding_store",
    "sellingPricePkr": 4999,
    "originalPrice": "Pro pricing varies by billing plan",
    "sourceUrl": "https://mobbin.com/pricing",
    "description": "Design-reference library access for researching real-world mobile and web interface patterns."
  },
  {
    "id": "p070",
    "slug": "autodesk-all-apps-34-apps",
    "category": "Education & Learning",
    "name": "Autodesk All Apps - 34 Apps",
    "duration": "3 Years",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 1999,
    "originalPrice": "All Apps official subscription pricing varies by region",
    "sourceUrl": "https://www.autodesk.com/collections/product-design-manufacturing/overview",
    "description": "Access package covering a broad Autodesk software collection for design, engineering and creative workflows."
  },
  {
    "id": "p071",
    "slug": "coursera-premium",
    "category": "Education & Learning",
    "name": "Coursera Premium",
    "duration": "12 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 1999,
    "originalPrice": "Coursera Plus $59/month or $399/year",
    "sourceUrl": "https://www.coursera.org/courseraplus",
    "description": "Online learning access for professional courses and educational content across technology, business and other fields."
  },
  {
    "id": "p072",
    "slug": "duolingo-super",
    "category": "Education & Learning",
    "name": "Duolingo Super",
    "duration": "1 Year",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 6999,
    "originalPrice": "Super pricing varies by region and plan",
    "sourceUrl": "https://www.duolingo.com/super",
    "description": "Premium language-learning plan with an enhanced, more convenient learning experience."
  },
  {
    "id": "p073",
    "slug": "github-student-developer-pack",
    "category": "Education & Learning",
    "name": "GitHub Student Developer Pack",
    "duration": "2 Years",
    "vendor": "EM Store",
    "sellingPricePkr": 4999,
    "originalPrice": "Student Developer Pack is free for eligible students",
    "sourceUrl": "https://education.github.com/pack",
    "description": "Developer-focused package providing access to coding, learning and software-development resources."
  },
  {
    "id": "p074",
    "slug": "amazon-prime-video",
    "category": "Entertainment & Streaming",
    "name": "Amazon Prime Video",
    "duration": "6 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 1499,
    "originalPrice": "$8.99/month standalone in the US",
    "sourceUrl": "https://www.primevideo.com/offers/nonprimehomepage/ref=dv_web_force_root",
    "description": "Video streaming access for movies, series and other Prime Video entertainment content."
  },
  {
    "id": "p075",
    "slug": "apple-music",
    "category": "Entertainment & Streaming",
    "name": "Apple Music",
    "duration": "5 Months",
    "vendor": "Dodi Store / CHIRAG OTT SHOP",
    "sellingPricePkr": 999,
    "originalPrice": "Individual $10.99/month",
    "sourceUrl": "https://www.apple.com/apple-music/",
    "description": "Music streaming access with a large song catalog, playlists, albums and personalized listening."
  },
  {
    "id": "p076",
    "slug": "netflix-4k-mail-access",
    "category": "Entertainment & Streaming",
    "name": "Netflix 4K Mail Access",
    "duration": "-",
    "vendor": "Dodi Store",
    "sellingPricePkr": 999,
    "originalPrice": "Premium plan price varies by country",
    "sourceUrl": "https://help.netflix.com/en/node/24926",
    "description": "Streaming access intended for watching Netflix movies, series and other entertainment content."
  },
  {
    "id": "p077",
    "slug": "spotify-premium",
    "category": "Entertainment & Streaming",
    "name": "Spotify Premium",
    "duration": "3 Months",
    "vendor": "Zoom Store",
    "sellingPricePkr": 1499,
    "originalPrice": "Individual Premium $11.99/month in the US",
    "sourceUrl": "https://www.spotify.com/us/premium/",
    "description": "Music and podcast streaming plan with premium playback features and an ad-free listening experience."
  },
  {
    "id": "p078",
    "slug": "spotify-premium-upgrade",
    "category": "Entertainment & Streaming",
    "name": "Spotify Premium Upgrade",
    "duration": "3 Months",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 1999,
    "originalPrice": "Individual Premium $11.99/month in the US",
    "sourceUrl": "https://www.spotify.com/us/premium/",
    "description": "Premium Spotify upgrade for enhanced music streaming and ad-free playback features."
  },
  {
    "id": "p079",
    "slug": "xbox-game-pass-ultimate",
    "category": "Entertainment & Streaming",
    "name": "Xbox Game Pass Ultimate",
    "duration": "1 Year",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 6999,
    "originalPrice": "Ultimate pricing varies by country",
    "sourceUrl": "https://www.xbox.com/en-US/xbox-game-pass",
    "description": "Gaming subscription providing access to a rotating game library and supported online gaming benefits."
  },
  {
    "id": "p080",
    "slug": "youtube-premium",
    "category": "Entertainment & Streaming",
    "name": "YouTube Premium",
    "duration": "3 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 1299,
    "originalPrice": "Individual from $13.99/month in the US",
    "sourceUrl": "https://www.youtube.com/premium",
    "description": "Premium YouTube access with ad-free viewing and enhanced playback features where supported."
  },
  {
    "id": "p081",
    "slug": "nordvpn",
    "category": "VPN & Privacy",
    "name": "NordVPN",
    "duration": "3 Months",
    "vendor": "Dodi Store / Gemini Shop",
    "sellingPricePkr": 1499,
    "originalPrice": "Official price varies by current plan and term",
    "sourceUrl": "https://nordvpn.com/pricing/",
    "description": "VPN service designed to encrypt internet traffic and improve privacy when browsing online."
  },
  {
    "id": "p082",
    "slug": "surfshark-vpn",
    "category": "VPN & Privacy",
    "name": "Surfshark VPN",
    "duration": "2 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 999,
    "originalPrice": "Official price varies by current plan and term",
    "sourceUrl": "https://surfshark.com/pricing",
    "description": "VPN service for encrypted browsing, privacy protection and secure internet connections."
  },
  {
    "id": "p083",
    "slug": "linkedin-all-in-one",
    "category": "Professional & Career",
    "name": "LinkedIn All-in-One",
    "duration": "3 Months",
    "vendor": "CHIRAG OTT SHOP",
    "sellingPricePkr": 6999,
    "originalPrice": "LinkedIn Premium pricing varies by plan",
    "sourceUrl": "https://www.linkedin.com/premium/products",
    "description": "Bundled LinkedIn premium-style access aimed at professional networking, career and business use cases."
  },
  {
    "id": "p084",
    "slug": "linkedin-business-premium",
    "category": "Professional & Career",
    "name": "LinkedIn Business Premium",
    "duration": "12 Months",
    "vendor": "Zoom Store",
    "sellingPricePkr": 19999,
    "originalPrice": "Business Premium around $59.99/month",
    "sourceUrl": "https://www.linkedin.com/premium/products",
    "description": "LinkedIn premium access aimed at business networking, professional research and relationship building."
  },
  {
    "id": "p085",
    "slug": "linkedin-business-new-user",
    "category": "Professional & Career",
    "name": "LinkedIn Business - New User",
    "duration": "2 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 1999,
    "originalPrice": "Business Premium around $59.99/month",
    "sourceUrl": "https://www.linkedin.com/premium/products",
    "description": "Business-oriented LinkedIn premium access for professional discovery, networking and company research."
  },
  {
    "id": "p086",
    "slug": "linkedin-career",
    "category": "Professional & Career",
    "name": "LinkedIn Career",
    "duration": "3 Months",
    "vendor": "Qamify",
    "sellingPricePkr": 1499,
    "originalPrice": "Career Premium around $39.99/month",
    "sourceUrl": "https://www.linkedin.com/premium/products",
    "description": "Career-focused LinkedIn premium access with job-search, applicant insights and professional networking features."
  },
  {
    "id": "p087",
    "slug": "linkedin-career-premium",
    "category": "Professional & Career",
    "name": "LinkedIn Career Premium",
    "duration": "12 Months",
    "vendor": "Zoom Store",
    "sellingPricePkr": 14999,
    "originalPrice": "Career Premium around $39.99/month",
    "sourceUrl": "https://www.linkedin.com/premium/products",
    "description": "Long-duration LinkedIn premium access focused on job searching, career insights and professional networking."
  },
  {
    "id": "p088",
    "slug": "cursor-pro-12-month-plan",
    "category": "Other Tools",
    "name": "Cursor Pro 12 Month Plan",
    "duration": "12 Months",
    "vendor": "Sasify Solutions",
    "sellingPricePkr": 29999,
    "originalPrice": "Cursor Pro from $20/month",
    "sourceUrl": "https://cursor.com/pricing",
    "description": "Twelve-month Cursor Pro access for AI-assisted coding, development and productivity workflows, available with one payment for the full 12-month plan."
  },
  {
    "id": "p089",
    "slug": "cursor-pro-api-400-credits-day",
    "category": "Other Tools",
    "name": "Cursor Pro API - 400 Credits/Day",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 4499,
    "originalPrice": "Cursor Pro from $20/month; API credit value depends on bundle",
    "sourceUrl": "https://cursor.com/pricing",
    "description": "Daily-credit Cursor API package for ongoing AI-assisted coding and development usage."
  },
  {
    "id": "p090",
    "slug": "cursor-pro-api-6-500-credits",
    "category": "Other Tools",
    "name": "Cursor Pro API - 6,500 Credits",
    "duration": "1 Month",
    "vendor": "PiggyAi_Bot",
    "sellingPricePkr": 6499,
    "originalPrice": "Cursor Pro from $20/month; API credit value depends on bundle",
    "sourceUrl": "https://cursor.com/pricing",
    "description": "Higher-credit Cursor API package intended for heavier AI coding and development usage."
  },
  {
    "id": "p091",
    "slug": "discord-nitro-basic",
    "category": "Other Tools",
    "name": "Discord Nitro Basic",
    "duration": "3 Months",
    "vendor": "Dodi Store",
    "sellingPricePkr": 999,
    "originalPrice": "$2.99/month",
    "sourceUrl": "https://discord.com/nitro",
    "description": "Discord premium tier with enhanced chat and profile features beyond the standard free experience."
  },
  {
    "id": "p092",
    "slug": "zoom-pro-trial",
    "category": "Other Tools",
    "name": "Zoom Pro Trial",
    "duration": "30 Days",
    "vendor": "FatBunny Hub",
    "sellingPricePkr": 2499,
    "originalPrice": "Pro from $15.99/month",
    "sourceUrl": "https://www.zoom.com/en/pricing/",
    "description": "Video-meeting plan for hosting online meetings with professional collaboration and conferencing features."
  }
];
